### ISSUE TITLE
Unhandled error while handling pm command

### ISSUE THREAD

**Issue by alistair23** [mautrix/signal#106]
After registering with signald I try to create a chat with

```
pm +6112345678
```

Where I get this error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 291, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/signal.py", line 77, in pm
    await portal.create_matrix_room(evt.sender, puppet.address)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 946, in create_matrix_room
    return await self._create_matrix_room(source, info)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1040, in _create_matrix_room
    self.mxid = await self.main_intent.create_room(name=name, is_direct=self.is_direct,
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 116, in create_room
    resp = await self.api.request(Method.POST, Path.createRoom, content)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 180, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MUnknown: Internal Server Error
```

I am unable to message any numbers with the same error. I'm using dendrite `0.4.0` as a homeserver and running signald and mautrix-signal inside Docker.

**Comment by alistair23** [comment]
This seems to be related to https://github.com/matrix-org/dendrite/issues/1882
