### ISSUE TITLE
Service crashing on start (worked fine for a few hours before)

### ISSUE THREAD

**Issue by TheCraiggers** [mautrix/signal#118]
New install via matrix-docker-ansible-deploy. Successfully bridged my account, chatted with one contact to test. After that, I went to install the Hangouts bridge, but ever since that restart of the services, the signal bridge crashes almost immediately. What follows is the error log from journalctl.

```
Aug 31 15:06:32 pebble systemd[1]: Starting Matrix Mautrix Signal server...
Aug 31 15:06:37 pebble systemd[1]: Started Matrix Mautrix Signal server.
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]: Traceback (most recent call last):
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     return _run_code(code, main_globals, None,
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     exec(code, run_globals)
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix_signal/__main__.py", line 152, in <module>
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     SignalBridge().run()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 83, in run
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self._prepare()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 89, in _prepare
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self.preinit()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 80, in preinit
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     super().preinit()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 109, in preinit
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self.prepare_config()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 96, in prepare_config
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self.load_and_update_config()
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 133, in load_and_update_config
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self.config.update(save=not self.args.no_update)
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/base.py", line 66, in update
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     self.do_update(ConfigUpdateHelper(base, self))
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix_signal/config.py", line 60, in do_update
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     copy("bridge.username_template")
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/base.py", line 26, in copy
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     if from_path in self.source:
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/recursive_dict.py", line 52, in __contains__
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     return self.get(key, None) is not None
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/recursive_dict.py", line 45, in get
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     return self._recursive_get(self._data, key, default_value)
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/recursive_dict.py", line 37, in _recursive_get
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     return self._recursive_get(next_data, next_key, default_value)
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:   File "/usr/lib/python3.9/site-packages/mautrix/util/config/recursive_dict.py", line 39, in _recursive_get
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]:     return data[key]
Aug 31 15:06:39 pebble matrix-mautrix-signal[167285]: TypeError: 'NoneType' object is not subscriptable
Aug 31 15:06:40 pebble systemd[1]: matrix-mautrix-signal.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 15:06:40 pebble systemd[1]: matrix-mautrix-signal.service: Failed with result 'exit-code'.
Aug 31 15:07:10 pebble systemd[1]: matrix-mautrix-signal.service: Scheduled restart job, restart counter is at 47.
Aug 31 15:07:10 pebble systemd[1]: Stopped Matrix Mautrix Signal server.
```

**Comment by TheCraiggers** [comment]
This was an issue with a malformed YAML when trying to setup my user. Sorry about the false report.
