### ISSUE TITLE
Command `register <E.164 formatted phone number>` returns a stack trace

### ISSUE THREAD

**Issue by Twi1ightSparkle** [mautrix/signal#119]
Steps to reproduce:
1. DM the Signal bot
2. Send `register <E.164 formatted phone number>` (+44 1234 567890 for example)
3. The Signal bot responds with:
> Unhandled error while handling command:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 291, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 113, in register
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
  File "/opt/mautrix-signal/mausignald/signald.py", line 104, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 221, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 215, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 212, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: NonSuccessfulResponseCodeException: [400] Bad response: 400 
```

**Comment by tulir** [comment]
There might be a better error message in signald logs, but it's also possible that Signal just doesn't like you (the error seems to be coming from the signal servers and passed through signald)

**Comment by derritter88** [comment]
You need to use the phone number without any spaces or other characters - e.g. +441234567890

So that whole command would be `register +441234567890`

Please keep in mind that it might be possible that you receive another error message asking for a captcha. If so you need to follow this step (only 1.) https://signald.org/articles/captcha/ and use that captcha code when registrating.

**Comment by felbinger** [comment]
![image](https://user-images.githubusercontent.com/26925347/141702308-7fcdad0c-6dcb-4519-9a27-687ce22ea114.png)

No spaces, no other characters, not asking for a capture - at least I'm unable to see it...

I noticed this problem a year ago when testing the bridge. I thought it had been fixed by now. Maybe the logs will help to solve this problem:
```
mautrix-signal_1    | [2021-11-14 22:55:13,607] [DEBUG@mau.mx] Received Matrix event $XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX from @username:mydomain.de in !qPXKcTsvANyoiXyQVb:mydomain.de
mautrix-signal_1    | [2021-11-14 22:55:14,622] [ERROR@mau.commands] Unhandled error while handling command register _PHONE_NUMBER_ from @username:mydomain.de (ref: 1636930472)
mautrix-signal_1    | Traceback (most recent call last):
mautrix-signal_1    |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 409, in handle
mautrix-signal_1    |     await self._run_handler(handler, evt)
mautrix-signal_1    |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 296, in __call__
mautrix-signal_1    |     return await self._handler(evt)
mautrix-signal_1    |   File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 113, in register
mautrix-signal_1    |     username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
mautrix-signal_1    |   File "/opt/mautrix-signal/mausignald/signald.py", line 120, in register
mautrix-signal_1    |     resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
mautrix-signal_1    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 223, in request_v1
mautrix-signal_1    |     return await self.request(command, expected_response=command, version="v1", **data)
mautrix-signal_1    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 217, in request
mautrix-signal_1    |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal_1    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 214, in _raw_request
mautrix-signal_1    |     return await asyncio.shield(future)
mautrix-signal_1    | mausignald.errors.ResponseError: CaptchaRequiredError: a captcha token is required to register
mautrix-signal_1    | [2021-11-14 22:55:14,770] [DEBUG@mau.mx] ResponseError('CaptchaRequiredError: a captcha token is required to register')
mautrix-signal_1    | [2021-11-14 22:55:14,770] [WARNING@mau.mx] Failed to send message send checkpoints for $XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: Constructor parameter should be str
mautrix-signal_1    | [2021-11-14 22:55:14,784] [INFO@aiohttp.access] 172.18.0.6 [14/Nov/2021:22:55:14 +0000] "PUT /transactions/6?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 200 158 "-" "Synapse/1.46.0"
```
```
signald_1           | 22:53:03.993 [main] INFO  io.finn.signald.Main - Binding to socket /signald/signald.sock
signald_1           | 22:53:04.011 [main] INFO  io.finn.signald.Main - Started signald 0.15.0-25-382c9a69
signald_1           | 22:54:31.516 [connection-pid-0] INFO  io.finn.signald.clientprotocol.ClientConnection - Client connected
signald_1           | 22:55:14.006 [543850df-b98e-4830-b52e-4d6f366387a6-register] INFO  io.finn.signald.RegistrationManager - Created a registration manager for *************
```

**Comment by tulir** [comment]
@felbinger that looks like a normal captcha required error, probably not related to this issue

**Comment by derritter88** [comment]
@felbinger Yes, as @tulir mentioned you need to get a captcha first of all --> https://signald.org/articles/captcha/

**Comment by felbinger** [comment]
@tulir @derritter88 thanks for clarification. It's working now.
