### ISSUE TITLE
RuntimeException: integer overflow during conversion of -1 to u32

### ISSUE THREAD

**Issue by gvcgael** [mautrix/signal#130]
Hello,

I'm trying to setup bridging with my signal account. After running the command `!signal link mautrix`, the bot correctly renders a QrCode. I associate with Signal, and then I get `Fatal error while waiting for linking to finish (see logs for more details)`.

Here are the logs from the containers. I'm running latest version of signald container and mautrix-signal container on an ARM64 machine :

```
        Container                     Repository                Tag        Image Id       Size  
------------------------------------------------------------------------------------------------
mautrix-signal               dock.mau.dev/mautrix/signal     latest      1e0cb7b5e7b3   211.6 MB
mautrix_db-signal_1          postgres                        13-alpine   eeffcec04820   183.4 MB
signald                      signald/signald                 latest      ac6d4ffa1a18   571.9 MB
```

```
signald             | 17:17:17.944 [main] INFO  io.finn.signald.Main - Binding to socket /signald/signald.sock
signald             | 17:17:18.068 [main] WARN  io.finn.signald.Main - No users are currently defined, you'll need to register or link to your existing signal account
signald             | 17:17:18.079 [main] INFO  io.finn.signald.Main - Started signald 0.14.1-44-4cabeeb5
mautrix-signal      | [2021-09-29 17:17:19,695] [INFO@mau.init] Initializing mautrix-signal 0.2.0+dev.2f26167c
mautrix-signal      | [2021-09-29 17:17:19,705] [INFO@mau.init] Initialization complete in 0.49 seconds
mautrix-signal      | [2021-09-29 17:17:19,706] [DEBUG@mau.init] Running startup actions...
mautrix-signal      | [2021-09-29 17:17:19,706] [DEBUG@mau.db] Connecting to postgres://mautrixsignal:fqgQTwLAUqW3vpuJjHy2jubvrTD5jePQ@db-signal/mautrixsignal
mautrix-signal      | [2021-09-29 17:17:19,876] [DEBUG@mau.init] Starting appservice...
mautrix-signal      | [2021-09-29 17:17:19,876] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29328
mautrix-signal      | [2021-09-29 17:17:19,879] [INFO@mau.mx] Ensuring connectivity to homeserver
mautrix-signal      | [2021-09-29 17:17:20,061] [DEBUG@mau.bridge.e2ee] Logging in with bridge bot user
mautrix-signal      | [2021-09-29 17:17:20,075] [DEBUG@mau.bridge.e2ee] Found device ID in database: GDATBHVQHG
mautrix-signal      | [2021-09-29 17:17:20,107] [INFO@mau.bridge.e2ee] End-to-bridge encryption support is enabled
mautrix-signal      | [2021-09-29 17:17:20,111] [DEBUG@mau.mx] Initializing appservice bot
mautrix-signal      | [2021-09-29 17:17:20,142] [DEBUG@mau.bridge.e2ee.client] Starting syncing
mautrix-signal      | [2021-09-29 17:17:20,209] [DEBUG@mau.periodic_sync] Periodic sync is not enabled
mautrix-signal      | [2021-09-29 17:17:20,210] [INFO@mau.init] Startup actions complete in 0.5 seconds, now running forever
signald             | 17:17:20.489 [connection-pid-0] INFO  io.finn.signald.clientprotocol.ClientConnection - Client connected
mautrix-signal      | [2021-09-29 17:17:20,634] [INFO@mausignald] Connected to signald v0.14.1-44-4cabeeb5
signald             | 17:17:46.874 [d032b478-9b1d-40a0-a89c-90417c0ea977-generate_linking_uri] INFO  generate_linking_uri - handled request d032b478-9b1d-40a0-a89c-90417c0ea977 successfully
signald             | 17:17:58.698 [fb20389e-0d1b-4c31-b999-2430aa61607a-finish_link] INFO  manager-**********************************c6 - Created a manager for **********************************c6
signald             | 17:17:58.869 [fb20389e-0d1b-4c31-b999-2430aa61607a-finish_link] ERROR finish_link - error while handling request
signald             | java.lang.RuntimeException: integer overflow during conversion of -1 to u32
signald             |   at org.signal.client.internal.Native.PreKeyRecord_New(Native Method) ~[signal-client-java-aarch64-unknown-linux-gnu-0.9.0.jar:?]
signald             |   at org.whispersystems.libsignal.state.PreKeyRecord.<init>(PreKeyRecord.java:25) ~[signal-client-java-aarch64-unknown-linux-gnu-0.9.0.jar:?]
signald             |   at io.finn.signald.Manager.generatePreKeys(Manager.java:260) ~[signald.jar:unspecified]
signald             |   at io.finn.signald.Manager.refreshPreKeys(Manager.java:288) ~[signald.jar:unspecified]
signald             |   at io.finn.signald.ProvisioningManager.finishDeviceLink(ProvisioningManager.java:108) ~[signald.jar:unspecified]
signald             |   at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:59) ~[signald.jar:unspecified]
signald             |   at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:38) ~[signald.jar:unspecified]
signald             |   at io.finn.signald.clientprotocol.Request.<init>(Request.java:158) [signald.jar:unspecified]
signald             |   at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:159) [signald.jar:unspecified]
signald             |   at java.lang.Thread.run(Unknown Source) [?:?]
mautrix-signal      | [2021-09-29 17:17:58,871] [ERROR@mau.commands] Fatal error while waiting for linking to finish
mautrix-signal      | Traceback (most recent call last):
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 68, in link
mautrix-signal      |     account = await evt.bridge.signal.finish_link(session_id=sess.session_id, overwrite=True,
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 116, in finish_link
mautrix-signal      |     resp = await self.request_v1("finish_link", device_name=device_name, session_id=session_id,
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 223, in request_v1
mautrix-signal      |     return await self.request(command, expected_response=command, version="v1", **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 217, in request
mautrix-signal      |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 214, in _raw_request
mautrix-signal      |     return await asyncio.shield(future)
mautrix-signal      | mausignald.errors.ResponseError: RuntimeException: integer overflow during conversion of -1 to u32
```

Any idea ?

**Comment by jrruethe** [comment]
I'm having this exact same error, though I am using the latest image on amd64, not arm.

**Comment by thefinn93** [comment]
please file an issue against signald: https://gitlab.com/signald/signald/-/issues

**Comment by klaasjanelzinga** [comment]
I have the same issue, filed an issue here https://gitlab.com/signald/signald/-/issues/222

**Comment by pomarec** [comment]
same

**Comment by thefinn93** [comment]
This has been resolved upstream and can probably be closed. Users who experienced this should delete the broken signald account, restart signald, then re-link.

**Comment by klaasjanelzinga** [comment]
Can confirm it is fixed.
