### ISSUE TITLE
Signal bridge crashing and maxing CPU usage (java.io.EOFException)

### ISSUE THREAD

**Issue by jakecoppinger** [mautrix/signal#161]
I'm seeing a very frequent (multiple times per second) errors like the following:

```
...
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.090 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onClose()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.095 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onFailure()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: java.io.EOFException
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.lang.Thread.run(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.096 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onClose()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.102 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onOpen() connected
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.119 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onFailure()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: java.io.EOFException
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]:         at java.base/java.lang.Thread.run(Unknown Source)
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.119 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] onClose()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.291 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] connect()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.296 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] connect()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.319 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG libsignal - [WebSocketConnection] connect()
Nov 04 13:48:57 jakes-matrix-server matrix-mautrix-signal-daemon[170166]: 02:48:57.560 [Thread-19909] DEBUG libsignal - [WebSocketConnection] Sending keep alive...
...
```

The CPU maxes out (on a relatively low end box, works nicely most of the time though) and I'm running the bridge via https://github.com/spantaleev/matrix-docker-ansible-deploy/

**Comment by jakecoppinger** [comment]
@tulir  Could I check if this issue has been specifically fixed? I currently reboot my server once a day to avoid the issue. Thanks :)

**Comment by sumnerevans** [comment]
You should update signald. We fixed that issue a few months ago now (it was a function that should have done exponential backoff, but didn't because of automatic type conversions).
