### ISSUE TITLE
Failed to update portal: UniqueViolationError: duplicate key value violates unique constraint "puppet_number_key"

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/signal#173]
```
[2021-11-18 12:18:53,670] [ERROR@mau.portal.some/id=] Failed to update portal
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1006, in update_matrix_room
    await self._update_matrix_room(source, info)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1052, in _update_matrix_room
    await self.update_info(source, info)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 844, in update_info
    await self._update_participants(source, info)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 939, in _update_participants
    await source.sync_contact(address)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/user.py", line 259, in sync_contact
    await puppet.update_info(profile)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/puppet.py", line 198, in update_info
    await self.handle_number_receive(address.number)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/puppet.py", line 134, in handle_number_receive
    await self._set_number(number)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/db/puppet.py", line 82, in _set_number
    await conn.execute("UPDATE puppet SET number=$1 WHERE uuid=$2", number, self.uuid)
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 317, in execute
    _, status, _ = await self._execute(
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 1639, in _execute
    result, _ = await self.__execute(
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 1664, in __execute
    return await self._do_execute(
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 1711, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "puppet_number_key"
DETAIL:  Key (number)=(+123456789) already exists.
```

**Comment by alistair23** [comment]
Same problem here
