### ISSUE TITLE
Unhandled error while handling command Logout

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/signal#201]
```
[2022-01-20 21:05:26,934] [ESC[31;1mERRORESC[0m@ESC[32mmau.commandsESC[0m] Unhandled error while handling command Logout  from @foo:bar (ref: barbaz)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 474, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 323, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 172, in logout
    await evt.sender.logout()
  File "/usr/lib/python3.9/site-packages/mautrix_signal/user.py", line 121, in logout
    await self.bridge.signal.unsubscribe(username)
  File "/opt/mautrix-signal/mausignald/signald.py", line 132, in unsubscribe
    self._subscriptions.remove(username)
KeyError: '+APhoneNumberIRemovedFromThisLog'
```

**Comment by sumnerevans** [comment]
Did the `unsubscribe` request to signald work? If so, we can probably just check that the username is in the set before removing.

**Comment by Half-Shot** [comment]
Hard to tell, signald doesn't appear to have logged anything. I suppose a lack of error logs is good news?

**Comment by nidico** [comment]
I had the same issue (maybe due to not using both the signal account and the bridge for several months, though I don't know for sure).

In my case the unsubscribe command succeeded - the signald log says:

    INFO  unsubscribe - handled request xxxxx successfully

Afterwards I was able to relink (as a new device).
