### ISSUE TITLE
Upgrading database from v3 to v4: Allow phone numbers as message sender identifiers

### ISSUE THREAD

**Issue by sudo-gedit** [mautrix/signal#204]
Hello friends,

Unfortunately, an error occurs when I want to start the bridge.
I don't understand exactly where the problem is. Can someone help?

xxxx@matrix:~/bridge_signal$ bin/python -m mautrix_signal
[2022-01-27 20:49:47,590] [INFO@mau.init] Initializing mautrix-signal 0.2.2
[2022-01-27 20:49:47,592] [INFO@mau.init] Initialization complete in 0.12 seconds
[2022-01-27 20:49:47,592] [DEBUG@mau.init] Running startup actions...
[2022-01-27 20:49:47,592] [DEBUG@mau.init] Starting database...
[2022-01-27 20:49:47,593] [DEBUG@mau.db] Connecting to postgres://xxxxx
[2022-01-27 20:49:47,612] [DEBUG@mau.db.upgrade] Upgrading database from v3 to v4: Allow phone numbers as message sender identifiers
[2022-01-27 20:49:47,616] [CRITICAL@mau.db] Failed to upgrade database
Traceback (most recent call last):
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 81, in start
    await self.upgrade_table.upgrade(self)
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/mautrix/util/async_db/upgrade.py", line 124, in upgrade
    await upgrade(conn, db.scheme)
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/mautrix_signal/db/upgrade.py", line 181, in upgrade_v4
    await conn.execute(f"ALTER TABLE reaction DROP CONSTRAINT {cname}")
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/mautrix/util/async_db/connection.py", line 35, in wrapper
    ret = await func(self, arg, *args, **kwargs)
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/mautrix/util/async_db/connection.py", line 68, in execute
    return await self.wrapped.execute(query, *args, timeout=timeout)
  File "/home/aengelmann/bridge_signal/lib/python3.9/site-packages/asyncpg/connection.py", line 318, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.UndefinedObjectError: constraint "none" of relation "reaction" does not exist

addendum:
xxxx@matrix:~/bridge_signal$ dpkg -l | grep synap
ii  matrix-synapse-py3                1.51.0+bullseye1               amd64        Open federated Instant Messaging and VoIP server

Best regards

**Comment by tulir** [comment]
Did you have the bridge running fine before, or are you trying to set it up with a non-empty database? If the latter, don't do that, separate programs require their own databases.

**Comment by sudo-gedit** [comment]
Oh that was a misunderstanding on my part.
I thought the bridge should access the synapse database.

Thanks for the help and maybe you can write a hint in the documentation.
