### ISSUE TITLE
Input validation error when attempting to link Dendrite server to Signal

### ISSUE THREAD

**Issue by thefirstofthe300** [mautrix/signal#207]
I am running a v0.6.0 Dendrite server and a v0.2.2 mautrix-signal bot. I have gotten the bot user registered on the server and am able to get into a room with the bot to submit commands. I'm now hitting the following error when attempting to run the `link` command:

```
[2022-01-29 07:02:10,569] [ERROR@mau.commands] Unhandled error while handling command link  from @firstofth300:dendrite.seymour.family (ref: 1643439728)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 474, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 323, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 75, in link
    sess = await evt.bridge.signal.start_link()
  File "/opt/mautrix-signal/mausignald/signald.py", line 151, in start_link
    return LinkSession.deserialize(await self.request_v1("generate_linking_uri"))
  File "/opt/mautrix-signal/mausignald/rpc.py", line 231, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 225, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 222, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: input validation failed, please check the request and try again.
[2022-01-29 07:02:10,617] [DEBUG@mau.mx] ResponseError('input validation failed, please check the request and try again.')
```

If I use the `version` command or the `help` command, no errors are thrown. I'm not sure what's up here and don't know if the issue is with Dendrite or the signal bridge.

**Comment by tulir** [comment]
This sounds like an outdated signald or something like that
