### ISSUE TITLE
Please support python 3.9

### ISSUE THREAD

**Issue by emorrp1** [mautrix/signal#208]
Hi, I've upgraded my host from Debian buster to bullseye, which replaces 3.7 with 3.9. However, the pypi version has a requires-python ~= 3.7 and I really doubt it's incompatible with 3.9:

```
$ pip install --verbose --upgrade mautrix-signal[all]
...
ERROR: Cannot install mautrix-signal[all]==0.1.0, mautrix-signal[all]==0.1.1, mautrix-signal[all]==0.2.0, mautrix-signal[all]==0.2.1 and mautrix-signal[all]==0.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    mautrix-signal[all] 0.2.2 depends on python-olm<4 and >=3; extra == "all"
    mautrix-signal[all] 0.2.1 depends on python-olm<4 and >=3; extra == "all"
    mautrix-signal[all] 0.2.0 depends on python-olm<4 and >=3; extra == "all"
    mautrix-signal[all] 0.1.1 depends on python-olm<4 and >=3; extra == "all"
    mautrix-signal[all] 0.1.0 depends on python-olm<4 and >=3; extra == "all"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Exception information:
Traceback (most recent call last):
  File "/srv/matrix-bridge/mautrix-signal/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    self._result = resolver.resolve(
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 357, in resolve
    raise ResolutionImpossible(causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('python-olm<4,>=3; extra == "all"'), parent=ExtrasCandidate(base=LinkCandidate('https://files.pythonhosted.org/packages/f4/af/7125a10a00b21a467a8b9f7377e10fb3bae65451782c56283ae433d20b51/mautrix_signal-0.2.2-py3-none-any.whl#sha256=da46a09e869f3cc0e56c2f66b7f11381c23c5fc6c28c0ec392514c9eb2dab244 (from https://pypi.org/simple/mautrix-signal/) (requires-python:~=3.7)'), extras=frozenset({'all'}))), RequirementInformation(requirement=SpecifierRequirement('python-olm<4,>=3; extra == "all"'), parent=ExtrasCandidate(base=LinkCandidate('https://files.pythonhosted.org/packages/31/42/c936000eb20a78427c3f5ea0de2dae0b2394f7ba817b42525b88f4f5bcc6/mautrix_signal-0.2.1-py3-none-any.whl#sha256=def2ff429daa77118fa2b59795f7f274cad37d1e044ae580434c9fbf87fa7438 (from https://pypi.org/simple/mautrix-signal/) (requires-python:~=3.7)'), extras=frozenset({'all'}))), RequirementInformation(requirement=SpecifierRequirement('python-olm<4,>=3; extra == "all"'), parent=ExtrasCandidate(base=LinkCandidate('https://files.pythonhosted.org/packages/08/25/082282e7cb03db5022567686516407d5a3f07b093cc461345cceb1a56270/mautrix_signal-0.2.0-py3-none-any.whl#sha256=96ef7d7ce5365135bd6121a48e6dc95425e1d13201ec7ee4f52de4cf65f6c32c (from https://pypi.org/simple/mautrix-signal/) (requires-python:~=3.7)'), extras=frozenset({'all'}))), RequirementInformation(requirement=SpecifierRequirement('python-olm<4,>=3; extra == "all"'), parent=ExtrasCandidate(base=LinkCandidate('https://files.pythonhosted.org/packages/27/05/4f115f688906cd172b57279dfa8d4ed9739796ea4540d0d24ff17f2ce0ba/mautrix_signal-0.1.1-py3-none-any.whl#sha256=b5481103a13fce927500c5313902fe6897f21fca8eac803a2d29d4860b87d225 (from https://pypi.org/simple/mautrix-signal/) (requires-python:~=3.7)'), extras=frozenset({'all'}))), RequirementInformation(requirement=SpecifierRequirement('python-olm<4,>=3; extra == "all"'), parent=ExtrasCandidate(base=LinkCandidate('https://files.pythonhosted.org/packages/5a/05/baf7f496c42ba61e1985818326a22cad1f83eaf3dfe06acdfbd6081f1b75/mautrix_signal-0.1.0-py3-none-any.whl#sha256=92e22a23cc7c54588f0f12b8aeb8e826b6b02bfbb2144c19ce4b1124cfc0482b (from https://pypi.org/simple/mautrix-signal/) (requires-python:~=3.7)'), extras=frozenset({'all'})))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/matrix-bridge/mautrix-signal/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/srv/matrix-bridge/mautrix-signal/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/srv/matrix-bridge/mautrix-signal/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 346, in run
    requirement_set = resolver.resolve(
  File "/srv/matrix-bridge/mautrix-signal/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Removed python-olm<4,>=3 from https://files.pythonhosted.org/packages/d4/a4/1face47e65118d7c52726dfa305410a96bc4a0c6f3f99c90bc7104aebf21/python-olm-3.1.3.tar.gz#sha256=9a6c6133ce3777788c88e3f18b13c5b36a2f76ed1a0e774d1a48adf542fee871 (from mautrix-signal[all]) from build tracker '/tmp/pip-req-tracker-ghjzgaev'
Removed python-olm<4,>=3 from https://files.pythonhosted.org/packages/3e/70/3e9fad24523ed2905d9c42ad1e2f1a3baedfbbc37e2ba3500c2d06cfa006/python-olm-3.1.0.tar.gz#sha256=eb7e022b805b4e7a0fb5af0aad6babce71c0cf2651282eaa2b32fc3781841c52 (from mautrix-signal[all]) from build tracker '/tmp/pip-req-tracker-ghjzgaev'
Removed build tracker: '/tmp/pip-req-tracker-ghjzgaev'

$ pip install --upgrade mautrix-signal[all] --no-dependencies
Collecting mautrix-signal[all]
  Using cached mautrix_signal-0.2.2-py3-none-any.whl (95 kB)
Installing collected packages: mautrix-signal
Successfully installed mautrix-signal-0.2.2
```

**Comment by tulir** [comment]
Python 3.9 is supported (3.10 is too). Not entirely sure what the error is actually saying, but it looks like some issue with olm

**Comment by emorrp1** [comment]
Hi tulir. You can see the requirement also listed on PyPI [Requires: Python ~=3.7](https://pypi.org/project/mautrix-signal/), compared to e.g. pip itself which says [Requires: Python >=3.7](https://pypi.org/project/pip/), I think it's just a publishing thing not a source code issue.

**Comment by tulir** [comment]
`~=3.7` means `>=3.7 && ==3.x` (which could also be written as `<4.0`)

https://www.python.org/dev/peps/pep-0440/#compatible-release
