### ISSUE TITLE
Cannot connect to database.

### ISSUE THREAD

**Issue by 71Zombie** [mautrix/signal#218]
I am running Mautrix in docker and am using the default credentials for testing purposes and I am receiving this error

```
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,361] [INFO@mau.init] Initializing mautrix-signal 0.2.2+dev.b7990630
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,365] [INFO@mau.init] Initialization complete in 0.36 seconds
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,365] [DEBUG@mau.init] Running startup actions...
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,366] [DEBUG@mau.init] Starting database...
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,366] [DEBUG@mau.db] Connecting to postgres://mautrixsignal:foobar@db/mautrixsignal
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | [2022-02-11 01:22:27,398] [CRITICAL@mau.init] Unexpected error in main event loop
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | Traceback (most recent call last):
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 219, in _run
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     self.loop.run_until_complete(self.start())
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return future.result()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/mautrix_signal/__main__.py", line 75, in start
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await super().start()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 174, in start
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await self.start_db()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 163, in start_db
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await self.db.start()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/mautrix/util/async_db/asyncpg.py", line 44, in start
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     self._pool = await asyncpg.create_pool(self.url, **self._db_args)
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 413, in _async__init__
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await self._initialize()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 441, in _initialize
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await first_ch.connect()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 133, in connect
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     self._con = await self._pool._get_new_connection()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     con = await connection.connect(
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 2085, in connect
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return await connect_utils._connect(
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return await _connect_addr(
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return await __connect_addr(params, timeout, True, *args)
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     await compat.wait_for(connected, timeout=timeout)
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return await asyncio.wait_for(fut, timeout)
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |   File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  |     return fut.result()
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal  | asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "mautrixsignal"
15f7fa03b0eb_15f7fa03b0eb_mautrix-signal exited with code 2
```

With my docker compose as follows

```

version: "3.7"

services:
  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal
    restart: unless-stopped
    volumes:
    - ./bridge:/data
    - ./signald:/signald
    depends_on:
    - signald

    # If synapse is running outside of docker, you'll need to expose the port.
    # Note that in most cases you should either run everything inside docker
    # or everything outside docker, rather than mixing docker things with
    # non-docker things.
    ports:
    - "29328:29328"
    # You'll also probably want this so the bridge can reach Synapse directly
    # using something like `http://host.docker.internal:8008` as the address:
#    extra_hosts:
#    - "http://host.docker.internal:8008"

    # If synapse is in a different network, then add this container to that network.
    # Note the networks object at the bottom too.
    #networks:
    #- default  # keep the container in the default network too so that the db container is reachable.
    #- synapsenet

  signald:
    container_name: signald
    image: docker.io/signald/signald
    restart: unless-stopped
    volumes:
    - ./signald:/signald
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mautrixsignal
      POSTGRES_DATABASE: foobar
      POSTGRES_PASSWORD: mautrixsignal
    volumes:
    - ./db:/var/lib/postgresql/data

# When synapse is in a different network (note the networks object in the service too):
#networks:
#  synapsenet:
#    external:
#      name: synapsenet

```

**Comment by tulir** [comment]
> POSTGRES_DATABASE: foobar
> POSTGRES_PASSWORD: mautrixsignal
