### ISSUE TITLE
Contact with no name

### ISSUE THREAD

**Issue by tpeacock19** [mautrix/signal#22]
I'm getting the following error upon startup with mautrix-signal

``` sh
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]: [2020-12-16 00:10:12,304] [#033[31;1mERROR#033[0m@#033[32mmau.user#033[0m.#033[33m@xxx:example.com#033[0m] Failed to sync contact Address(number='+15555555555', uuid=UUID('[redacted]'))
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]: Traceback (most recent call last):
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:   File "/home/matrix-synapse/synapse/appservice/mautrix-signal/.venv/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:     obj = attrs_type(**new_items)
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]: TypeError: __init__() missing 1 required positional argument: 'name'
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]: The above exception was the direct cause of the following exception:
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]: Traceback (most recent call last):
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:   File "/home/matrix-synapse/synapse/appservice/mautrix-signal/mautrix_signal/user.py", line 149, in _sync
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:     await self._sync_contact(contact, create_contact_portal)
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:   File "/home/matrix-synapse/synapse/appservice/mautrix-signal/mautrix_signal/user.py", line 117, in _sync_contact
Dec 16 00:10:12 matrix matrix-puppet-signal[7701]:     profile = await self.bridge.signal.get_profile(self.username, contact.address)

```

I queried signald directly and it does return a profile without a username. Is there any way to handle this without throwing the error given that I cannot control if a contact has a username or not.

``` sh
Query
{"id": "[redacted]", "type": "get_profile", "username": "+15555555555", "recipientAddress": {"number": "+15555555555", "uuid": "[redacted]"}}

Response
{"id":"[redacted]","type":"profile","data":{"avatar":"profiles/6sqWm3ddnOtfEl66qwN-Kw","identity_key":"Bdnmjoa3hqHxoadL9X1jNaTCFxKjgXEK03GaYqcQYd01","unidentified_access":"y7umzyJKQlTIXPpLlLx5wPdMPvoXb3BdUGiRpP/E0l0=","unrestricted_unidentified_access":false,"capabilities":{"gv2":false,"storage":false,"gv1-migration":false},"address":{"number":"+15555555555","uuid":"[redacted]"}}}


```

Additionally, How can you force the bridge to update profile displaynames? It seems I always need to update displaynames manually.

**Comment by rhyst** [comment]
I also don't seem to get usernames. I can't access the logs though because the docker image doesn't seem to have logging set up?

**Comment by jld3103** [comment]
Same here. Configured to show names, but only shows the phone numbers

**Comment by tchapi** [comment]
Same here, any workaround ?

**Comment by tchapi** [comment]
https://github.com/tulir/mautrix-signal/issues/56#issuecomment-803911136 might be linked

**Comment by goatstpokemon** [comment]
same all I see is phone numbers

**Comment by jakobod** [comment]
Is there any solution to this problem? I have the same problem..

**Comment by jakobod** [comment]
Seems like waiting fixed the problem for me. All my chats have simply synced up now and show their display names!
