### ISSUE TITLE
Check that room is still usable in `pm` command

### ISSUE THREAD

**Issue by tulir** [mautrix/signal#232]
If the user did something dumb (like kicking the bridge or deleting the room with the homeserver admin API), the existing DM portal room might not be usable anymore. The bridge should detect that in the `pm` command and create a new room.

**Comment by jaller94** [comment]
We have a case where the bridge fails to handle a `pm` command because it's not in the room.
I replaced all sensitive values with `foo`.

```
[2022-03-31 15:48:04,227] [DEBUG@mau.mx] Received Matrix event $foofoofoofoofoofoofoofoofoofoo from @foo:one.ems.host in !foofoofoofoo:one.ems.host
[2022-03-31 15:48:04,530] [ERROR@mau.commands] Unhandled error while handling command Pm +49foofoofoo from @foo:one.ems.host (ref: 1648661830)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 229, in invite_user
    await super().invite_user(
  File "/usr/lib/python3.9/site-packages/mautrix/client/store_updater.py", line 87, in invite_user
    await super().invite_user(room_id, user_id, reason, extra_content=extra_content)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 434, in invite_user
    await self.api.request(Method.POST, Path.rooms[room_id].invite, content=data)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 359, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 256, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: You don't have permission to invite users

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 474, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 323, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/signal.py", line 92, in pm
    await portal.main_intent.invite_user(portal.mxid, evt.sender.mxid)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 135, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 237, in invite_user
    raise IntentError(f"Failed to invite {user_id} to {room_id}", e)
mautrix.errors.base.IntentError: ('Failed to invite @foo:one.ems.host to !foo:one.ems.host', MForbidden("You don't have permission to invite users"))
[2022-03-31 15:48:04,581] [DEBUG@mau.mx] IntentError('Failed to invite @foo:one.ems.host to !foo:one.ems.host', MForbidden("You don't have permission to invite users"))
```

**Comment by shukon** [comment]
This happens to my users all the time. It's hard to fix without access to the accounts and always requires fiddling the database, so this would be highly useful and appreciated. :heart:

**Comment by Craeckie** [comment]
The problem persists in v0.4.0.

In case you use postgres, the following might help to fix it:
List the databases: `\list`
Open the database: `\c signal_bridge`
List all portals: `SELECT * FROM portal;`
Find the one that is broken (see the exception): 
`SELECT * FROM portal WHERE mxid='!foo:one.ems.host';`
Double check and delete it: `DELETE FROM portal WHERE mxid='!foo:one.ems.host';`
Restart the bridge and recreate the room with `pm +123123123`

(this is also for myself in case it happens again)

**Comment by zmbcgn** [comment]
The problem also persists in the go rewrite: mautrix-signal 0.4.99+dev.717e58cb 

thanks to craeckie for the guide.
