### ISSUE TITLE
Missed first message in a group that had a video attachment due to recursive SQLite Transactions

### ISSUE THREAD

**Issue by TheBlueMatt** [mautrix/signal#237]
The first message I had in a group since installing mautrix-signal had a video attachment, and generated the following stacktrace (and that first message was lost).

```
[2022-04-03 03:00:16,654] [ERROR@mausignald] Exception in event handler
Traceback (most recent call last):
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mausignald/signald.py", line 75, in _run_ev
ent_handler
    await handler(event)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/signal.py", line 73, in on_m
essage
    await self.handle_message(user, sender, evt.data_message)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/signal.py", line 192, in han
dle_message
    await portal.create_matrix_room(
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1452, in cr
eate_matrix_room
    return await self._create_matrix_room(source, info)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1608, in _c
reate_matrix_room
    await self._update_participants(source, info)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1355, in _u
pdate_participants
    await source.sync_contact(address)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/user.py", line 297, in sync_contact
    await puppet.update_info(profile)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/puppet.py", line 236, in update_info
    await self.handle_number_receive(address.number)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/puppet.py", line 169, in handle_number_receive
    await self._set_number(number)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/db/puppet.py", line 94, in _set_number
    await self._update_number_to_uuid(conn, number, str(self.uuid))
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/db/puppet.py", line 101, in _update_number_to_uuid
    async with conn.transaction():
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix/util/async_db/connection.py", line 63, in transaction
    async with self.wrapped.transaction():
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix/util/async_db/aiosqlite.py", line 36, in transaction
    await self.execute("BEGIN TRANSACTION")
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/mautrix/util/async_db/aiosqlite.py", line 50, in execute
    await self.__execute(query, *args)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/path/to/mautrix-signal/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: cannot start a transaction within a transaction
```

**Comment by tulir** [comment]
SQLite isn't properly supported yet
