### ISSUE TITLE
Registration fails due to foreign key constraint signald_account_data_account_uuid_fkey

### ISSUE THREAD

**Issue by vranki** [mautrix/signal#247]
Trying to use register command with up to date bridge. I had to use the captcha tool to get the captcha key.

register --captcha <captcha> <number> seems to succeed and replies with "Register SMS requested, please enter the code here."

After sending the SMS code I got:

```
Traceback (most recent call last):
  File "/opt/signalbot/lib/python3.9/site-packages/mautrix/bridge/commands/[handler.py](http://handler.py/)", line 474, in handle
    await self._run_handler(handler, evt)
  File "/opt/signalbot/lib/python3.9/site-packages/mautrix_signal/commands/[auth.py](http://auth.py/)", line 148, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/signalbot/lib/python3.9/site-packages/mausignald/[signald.py](http://signald.py/)", line 156, in verify
    resp = await self.request_v1("verify", account=username, code=code)
  File "/opt/signalbot/lib/python3.9/site-packages/mausignald/[rpc.py](http://rpc.py/)", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/signalbot/lib/python3.9/site-packages/mausignald/[rpc.py](http://rpc.py/)", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/signalbot/lib/python3.9/site-packages/mausignald/[rpc.py](http://rpc.py/)", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: org.postgresql.util.PSQLException: org.postgresql.util.PSQLException: ERROR: insert or update on table "signald_account_data" violates foreign key constraint "signald_account_data_account_uuid_fkey"
  Detail: Key (account_uuid)=(4855xxxx-9xxx-4d76-bb42-d95ab26xxxxxx) is not present in table "signald_accounts".
  ```

Not sure how to continue from this.

**Comment by vranki** [comment]
Filed an issue on signald at https://gitlab.com/signald/signald/-/issues/315

**Comment by vranki** [comment]
Fixed with upstream signald change.
