### ISSUE TITLE
ProofRequiredException

### ISSUE THREAD

**Issue by dasJ** [mautrix/signal#261]
I opened a new DM and tried to send a message, the bridge replied with:
```
⚠ Your message was not bridged: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
```

The logs show:
```
May 23 23:39:26 rambutan signald[856708]: 23:39:26.165 [e4796c8a-f7b3-47d0-b63a-ef8ac3336cdb-send] ERROR io.finn.signald.clientprotocol.v1.exceptions.InternalError - error sending message
May 23 23:39:26 rambutan signald[856708]: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1755) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1706) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1688) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1677) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1613) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1607) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:530) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1804) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:347) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_41.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.Manager.sendMessage(Manager.java:642) ~[signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.Manager.send(Manager.java:765) ~[signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.clientprotocol.v1.Common.send(Common.java:163) [signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.clientprotocol.v1.SendRequest.run(SendRequest.java:164) [signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.clientprotocol.v1.SendRequest.run(SendRequest.java:44) [signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:147) [signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) [signald.jar:?]
May 23 23:39:26 rambutan signald[856708]:         at java.lang.Thread.run(Thread.java:833) [?:?]
May 23 23:39:26 rambutan mautrix-signal[711154]: [ERROR@mau.portal.dbe26173-2127-408b-bd62-515fdcb3753a] Sending message failed
May 23 23:39:26 rambutan mautrix-signal[711154]: Traceback (most recent call last):
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mautrix_signal/portal.py", line 409, in _handle_matrix_message
May 23 23:39:26 rambutan mautrix-signal[711154]:     retry_count = await self._signal_send_with_retries(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mautrix_signal/portal.py", line 478, in _signal_send_with_retries
May 23 23:39:26 rambutan mautrix-signal[711154]:     await send_fn(sender, event_id, req_id=req_id, **send_args)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/signald.py", line 251, in send
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp = await self.send_raw(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/signald.py", line 225, in send_raw
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp = await self.request_v1(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
May 23 23:39:26 rambutan mautrix-signal[711154]:     return await self._request(command, expected_response=command, version="v1", **data)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp_type, resp_data = await self._raw_request(command, **data)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
May 23 23:39:26 rambutan mautrix-signal[711154]:     return await asyncio.shield(future)
May 23 23:39:26 rambutan mautrix-signal[711154]: mausignald.errors.InternalError: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
May 23 23:39:26 rambutan mautrix-signal[711154]: [ERROR@mau.portal.dbe26173-2127-408b-bd62-515fdcb3753a] Failed to handle Matrix message $WIdqEOOufqcnyQCR4qA0niaFvS8D7_drr_jh5V7-swc
May 23 23:39:26 rambutan mautrix-signal[711154]: Traceback (most recent call last):
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mautrix_signal/portal.py", line 310, in handle_matrix_message
May 23 23:39:26 rambutan mautrix-signal[711154]:     await self._handle_matrix_message(sender, message, event_id)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mautrix_signal/portal.py", line 409, in _handle_matrix_message
May 23 23:39:26 rambutan mautrix-signal[711154]:     retry_count = await self._signal_send_with_retries(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mautrix_signal/portal.py", line 478, in _signal_send_with_retries
May 23 23:39:26 rambutan mautrix-signal[711154]:     await send_fn(sender, event_id, req_id=req_id, **send_args)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/signald.py", line 251, in send
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp = await self.send_raw(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/signald.py", line 225, in send_raw
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp = await self.request_v1(
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
May 23 23:39:26 rambutan mautrix-signal[711154]:     return await self._request(command, expected_response=command, version="v1", **data)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
May 23 23:39:26 rambutan mautrix-signal[711154]:     resp_type, resp_data = await self._raw_request(command, **data)
May 23 23:39:26 rambutan mautrix-signal[711154]:   File "/nix/store/7vl9v2jdhzxq5xi4xbj82655qn7x28fy-python3.9-mautrix-signal-0.3.0/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
May 23 23:39:26 rambutan mautrix-signal[711154]:     return await asyncio.shield(future)
May 23 23:39:26 rambutan mautrix-signal[711154]: mausignald.errors.InternalError: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: org.whispersystems.signalservice.api.push.exceptions.ProofRequiredException: StatusCode: 428
```

I am really out of ideas and looking through the internet doesn't give me anything relevant.

**Comment by thefinn93** [comment]
You're getting rate limited and need to complete a captcha. Trying to send a message to the same recipient from the Signal app with do this. There are other options if you can't/don't want to use the Signal app

**Comment by dasJ** [comment]
So add the signal app as a second device? Because I currently only have signald as a device

**Comment by thefinn93** [comment]
Yeah you'd have to add Signal Desktop, since the mobile apps can't be used as a non-primary device. You could also use [signaldctl](https://signald.org/signaldctl/reference/signaldctl_message_send/)'s `--captcha-helper` option to get it to show you the captcha. Note that you will need to have a graphical system available and [signal-captcha-helper](https://gitlab.com/signald/captcha-helper) in the path.

**Comment by tomnick** [comment]
Same problem here. Signal bridge was working fine until I changed smartphones. Now I am getting the same error as above. I tried the solutions mentioned here but nothing worked. Anybody have any other solution?

My client is Element
