### ISSUE TITLE
mautrix.errors.request.MUnknown: More than one row matched (users)

### ISSUE THREAD

**Issue by nmattela** [mautrix/signal#271]
I have been getting an error after redeploying matrix and the bridges on my kubernetes cluster. I use synapse and the dock.mau.dev/mautrix/signal and docker.io/signald/signald docker images respectively. The error seems to appear during any Matrix activity (when I send or receive messages, with or without using the signal bridge). The full logs are:

```
[2022-06-13 20:34:36,096] [INFO@mau.init] Initializing mautrix-signal 0.3.0+dev.18fb20c4
[2022-06-13 20:34:36,103] [INFO@mau.init] Initialization complete in 0.27 seconds
[2022-06-13 20:34:36,103] [DEBUG@mau.init] Running startup actions...
[2022-06-13 20:34:36,104] [DEBUG@mau.init] Starting database...
[2022-06-13 20:34:36,104] [DEBUG@mau.db] Connecting to postgres://signal@127.0.0.1/signal
[2022-06-13 20:34:36,147] [DEBUG@mau.db.upgrade] Database at v9, not upgrading
[2022-06-13 20:34:36,151] [DEBUG@mau.client.db.upgrade] Database at v2, not upgrading
[2022-06-13 20:34:36,151] [DEBUG@mau.init] Starting appservice...
[2022-06-13 20:34:36,151] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29328
[2022-06-13 20:34:36,153] [INFO@mau.mx] Ensuring connectivity to homeserver
[2022-06-13 20:34:36,214] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:34:46,243] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:34:56,263] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:35:06,287] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:35:16,312] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:35:26,331] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
[2022-06-13 20:35:36,353] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 221, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/mautrix_signal/__main__.py", line 75, in start
    await super().start()
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 211, in start
    await self.matrix.wait_for_connection()
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 159, in wait_for_connection
    await self.az.intent.whoami()
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: More than one row matched (users)
```
The first few errors is just the bridge attempting to connect to the homeserver, that seems pretty normal. It's the last error message (Unexpected error in main event loop) which is concerning.

**Comment by nmattela** [comment]
Seems something was up with Synapse. Signal bridge detected it, but all the other bridges didn't for some reason. The issue was completely unrelated to the bridge so it will probably not help you, but the database was concurrently being accessed. Lowering and then upping the version of Synapse seemed to have fixed it for some strange reason... Sorry for opening this issue.
