### ISSUE TITLE
Unable to link a device

### ISSUE THREAD

**Issue by rajil** [mautrix/signal#290]
I am trying to link a device by scanning QRcode but get an error,

```
Aug 09 23:20:35 matrix mautrix-signal[8867]: [2022-08-09 23:20:35,329] [DEBUG@mausignald] Request 5ec870e7-2258-4250-a721-8a3893349004: generate_linking_uri
Aug 09 23:20:43 matrix mautrix-signal[8867]: [2022-08-09 23:20:43,162] [DEBUG@mausignald] Request d056282c-df9a-4da8-9240-376ffad146e5: finish_link
Aug 09 23:20:43 matrix mautrix-signal[8867]: [2022-08-09 23:20:43,401] [INFO@aiohttp.access] 127.0.0.1 [09/Aug/2022:17:50:43 +0000] "PUT /transactions/2440050?access_token=9URKG2ExVtR3POAJ7W7T-L- HTTP/1.1" 200 158 "-" "Synapse/1.64.0"
Aug 09 23:20:50 matrix mautrix-signal[8867]: [2022-08-09 23:20:50,011] [ERROR@mau.commands] Fatal error while waiting for linking to finish
Aug 09 23:20:50 matrix mautrix-signal[8867]: Traceback (most recent call last):
Aug 09 23:20:50 matrix mautrix-signal[8867]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 79, in link
Aug 09 23:20:50 matrix mautrix-signal[8867]:     account = await evt.bridge.signal.finish_link(
Aug 09 23:20:50 matrix mautrix-signal[8867]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/signald.py", line 168, in finish_link
Aug 09 23:20:50 matrix mautrix-signal[8867]:     resp = await self.request_v1(
Aug 09 23:20:50 matrix mautrix-signal[8867]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 244, in request_v1
Aug 09 23:20:50 matrix mautrix-signal[8867]:     return await self._request(command, expected_response=command, version="v1", **data)
Aug 09 23:20:50 matrix mautrix-signal[8867]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 238, in _request
Aug 09 23:20:50 matrix mautrix-signal[8867]:     resp_type, resp_data = await self._raw_request(command, **data)
Aug 09 23:20:50 matrix mautrix-signal[8867]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 235, in _raw_request
Aug 09 23:20:50 matrix mautrix-signal[8867]:     return await asyncio.shield(future)
Aug 09 23:20:50 matrix mautrix-signal[8867]: mausignald.errors.InternalError: java.io.FileNotFoundException: java.io.FileNotFoundException: /var/lib/signald/data/+12345 (No such file or directory)
```
Any idea what is wrong?

**Comment by mborho** [comment]
Same problem here...

**Comment by brotkastn** [comment]
I had to switch my smartphone, and could not log out the bridge. I managed to migrate signal to the new phone, because i had a backup.
However, i am unable to link the signal to the new device. The (docker) logs show the following:
```
mautrix-signal    | [2022-08-29 12:55:44,910] [DEBUG@mausignald] Request 6a62f846-6acd-467b-958e-5aa77a51a30d: finish_link
mautrix-signal    | [2022-08-29 12:55:44,954] [INFO@aiohttp.access] 172.19.0.1 [29/Aug/2022:12:55:44 +0000] "PUT /transactions/8376?access_token=lFQMvTI6HRomPRqwDVQQkSeO2z6h8861-tq7vQJ9Ff11chn_WMNoF9R-Rd_dFaCO HTTP/1.1" 200 159 "-" "Synapse/1.65.0"
signald           | 12:55:55.071 [6a62f846-6acd-467b-958e-5aa77a51a30d-finish_link] INFO  manager-**********************************90 - Created a manager for **********************************90
signald           | 12:55:56.499 [6a62f846-6acd-467b-958e-5aa77a51a30d-finish_link] INFO  manager-**********************************90 - Created a manager for **********************************90
signald           | 12:55:56.582 [6a62f846-6acd-467b-958e-5aa77a51a30d-finish_link] INFO  io.finn.signald.jobs.RefreshPreKeysJob - generating pre keys
signald           | 12:56:07.080 [6a62f846-6acd-467b-958e-5aa77a51a30d-finish_link] ERROR io.finn.signald.clientprotocol.v1.exceptions.InternalError - error finishing linking
signald           | org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1758) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1735) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1717) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1706) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1642) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1618) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerPreKeys(PushServiceSocket.java:595) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at org.whispersystems.signalservice.api.SignalServiceAccountManager.setPreKeys(SignalServiceAccountManager.java:437) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
signald           |     at io.finn.signald.jobs.RefreshPreKeysJob.refreshPreKeys(RefreshPreKeysJob.java:72) ~[signald.jar:?]
signald           |     at io.finn.signald.jobs.RefreshPreKeysJob.run(RefreshPreKeysJob.java:45) ~[signald.jar:?]
signald           |     at io.finn.signald.ProvisioningManager.finishDeviceLink(ProvisioningManager.java:125) ~[signald.jar:?]
signald           |     at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:52) ~[signald.jar:?]
signald           |     at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:30) ~[signald.jar:?]
signald           |     at io.finn.signald.clientprotocol.Request.<init>(Request.java:146) ~[signald.jar:?]
signald           |     at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) ~[signald.jar:?]
signald           |     at java.lang.Thread.run(Unknown Source) ~[?:?]
mautrix-signal    | [2022-08-29 12:56:07,092] [ERROR@mau.commands] Fatal error while waiting for linking to finish
mautrix-signal    | Traceback (most recent call last):
mautrix-signal    |   File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 119, in link
mautrix-signal    |     account = await evt.bridge.signal.finish_link(
mautrix-signal    |   File "/opt/mautrix-signal/mausignald/signald.py", line 176, in finish_link
mautrix-signal    |     resp = await self.request_v1(
mautrix-signal    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
mautrix-signal    |     return await self._request(command, expected_response=command, version="v1", **data)
mautrix-signal    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
mautrix-signal    |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal    |   File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
mautrix-signal    |     return await asyncio.shield(future)
mautrix-signal    | mausignald.errors.InternalError: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!

```
I found this bug using the errors in this log. Is there anything i can do so i can use the signal-bridge again?

Thank you for your work,
Michael

**Comment by thefinn93** [comment]
@brotkastn that looks like signald issue [#336](https://gitlab.com/signald/signald/-/issues/336). I would love it if you could try the latest `:unstable` signald build and let me know (ideally in that signald issue) what the logs say when you try to link again.

**Comment by 0spinboson** [comment]
also having this issue. Would appreciate it if it could be fixed.

**Comment by thefinn93** [comment]
see [signald issue](https://gitlab.com/signald/signald/-/issues/379)

**Comment by tulir** [comment]
Searching for old issues before creating new ones is good, but replying on old issues that are already closed is not.

This issue is not related to the 405 error caused by signal changing their linking API recently. The bridge has also been rewritten and the 405 issue doesn't exist on the main branch.
