### ISSUE TITLE
ProfileUnavailableError: profile unavailable

### ISSUE THREAD

**Issue by rajil** [mautrix/signal#291]
This is a new installation of mautrix-signal. It did not create a portal for me. However, i get the following error on startup,

```
 Aug 11 23:07:36 matrix mautrix-signal[186]: [2022-08-11 23:07:36,438] [ERROR@mau.portal.tpYGIBBERISHY=] Failed to update portal
Aug 11 23:07:36 matrix mautrix-signal[186]: Traceback (most recent call last):
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 1536, in update_matrix_room
Aug 11 23:07:36 matrix mautrix-signal[186]:     await self._update_matrix_room(source, info)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 1595, in _update_matrix_room
Aug 11 23:07:36 matrix mautrix-signal[186]:     await self.update_info(source, info)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 1300, in update_info
Aug 11 23:07:36 matrix mautrix-signal[186]:     await self._update_participants(source, info)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 1451, in _update_participants
Aug 11 23:07:36 matrix mautrix-signal[186]:     await source.sync_contact(address)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/user.py", line 295, in sync_contact
Aug 11 23:07:36 matrix mautrix-signal[186]:     profile = await self.bridge.signal.get_profile(
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/signald.py", line 398, in get_profile
Aug 11 23:07:36 matrix mautrix-signal[186]:     resp = await self.request_v1(
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 244, in request_v1
Aug 11 23:07:36 matrix mautrix-signal[186]:     return await self._request(command, expected_response=command, version="v1", **data)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 238, in _request
Aug 11 23:07:36 matrix mautrix-signal[186]:     resp_type, resp_data = await self._raw_request(command, **data)
Aug 11 23:07:36 matrix mautrix-signal[186]:   File "/opt/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 235, in _raw_request
Aug 11 23:07:36 matrix mautrix-signal[186]:     return await asyncio.shield(future)
Aug 11 23:07:36 matrix mautrix-signal[186]: mausignald.errors.ResponseError: ProfileUnavailableError: profile unavailable
```

Can this be fixed?

**Comment by tulir** [comment]
Looks like an old version of the bridge

**Comment by rajil** [comment]
Version number is mautrix-signal 0.3.0

**Comment by maltee1** [comment]
@tulir there hasn't been a release since this was fixed.
The release is just very outdated ;)
