### ISSUE TITLE
Bridge fails to startup with DB schema v11

### ISSUE THREAD

**Issue by olmari** [mautrix/signal#305]
Versions:
Old: 0.4.0
New: 0.4.0+dev.f68e2a8b

https://github.com/mautrix/signal/commit/2ec415648c61908ee90b4714ec8c54debfb9b42e I suspect is the change, after this our Mautrix-signal no longer starts up but errors out apparently in DB schema update time:

```
Sep 23 19:52:53 morpheus python[708084]: [2022-09-23 19:52:53,478] [DEBUG@mau.db.upgrade] Upgrading database from v10 to v11: Drop support for phone numbers as puppet identifiers
Sep 23 19:52:53 morpheus python[708084]: [2022-09-23 19:52:53,632] [CRITICAL@mau.init] Failed to initialize database
Sep 23 19:52:53 morpheus python[708084]: Traceback (most recent call last):
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 199, in start_db
Sep 23 19:52:53 morpheus python[708084]:     await self.db.start()
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/util/async_db/asyncpg.py", line 72, in start
Sep 23 19:52:53 morpheus python[708084]:     await super().start()
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 105, in start
Sep 23 19:52:53 morpheus python[708084]:     await self.upgrade_table.upgrade(self)
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/util/async_db/upgrade.py", line 137, in upgrade
Sep 23 19:52:53 morpheus python[708084]:     version = await upgrade(conn, db.scheme) or new_version
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix_signal/db/upgrade/v11_drop_number_support.py", line 57, in upgrade_v11
Sep 23 19:52:53 morpheus python[708084]:     await conn.execute(
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
Sep 23 19:52:53 morpheus python[708084]:     ret = await func(self, arg, *args, **kwargs)
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/util/async_db/connection.py", line 81, in execute
Sep 23 19:52:53 morpheus python[708084]:     return await self.wrapped.execute(query, *args, timeout=timeout)
Sep 23 19:52:53 morpheus python[708084]:   File "/opt/signalbot/lib/python3.9/site-packages/asyncpg/connection.py", line 318, in execute
Sep 23 19:52:53 morpheus python[708084]:     return await self._protocol.query(query, timeout)
Sep 23 19:52:53 morpheus python[708084]:   File "asyncpg/protocol/protocol.pyx", line 338, in query
Sep 23 19:52:53 morpheus python[708084]: asyncpg.exceptions.ForeignKeyViolationError: insert or update on table "message" violates foreign key constraint "message_sender_fkey"
Sep 23 19:52:53 morpheus python[708084]: DETAIL:  Key (sender)=(<UUID>) is not present in table "puppet".
Sep 23 19:52:53 morpheus systemd[1]: signalbot.service: Main process exited, code=exited, status=25/n/a
Sep 23 19:52:53 morpheus systemd[1]: signalbot.service: Failed with result 'exit-code'.
Sep 23 19:52:53 morpheus systemd[1]: signalbot.service: Scheduled restart job, restart counter is at 5.
Sep 23 19:52:53 morpheus systemd[1]: Stopped Mautrix-Signal bridge bot.
Sep 23 19:52:53 morpheus systemd[1]: signalbot.service: Start request repeated too quickly.
Sep 23 19:52:53 morpheus systemd[1]: signalbot.service: Failed with result 'exit-code'.
Sep 23 19:52:53 morpheus systemd[1]: Failed to start Mautrix-Signal bridge bot.
```

Rolling back to version 90542f770fe4910df2df9f43734de4a777691860 makes it run again.

**Comment by olmari** [comment]
Fixed with https://github.com/mautrix/signal/commit/2798e463ca6774d8199944aa9dbc588d61b310bf
