### ISSUE TITLE
Cannot send messages via signal room between two double-puppeted users

### ISSUE THREAD

**Issue by alexmaras** [mautrix/signal#310]
Using double-puppeting with two users on one matrix server and trying to send messages via the shared signal rooms fails with the following error. The messages go through to signal without an issue, but don't appear in the other person's matrix client. It appears that the double-puppet user (setup using `login_shared_secret_map` configuration) can't gain access to the room.

```
matrix-bridge-signal-1      | [2022-09-30 03:18:02,639] [ERROR@mausignald] Exception in event handler
matrix-bridge-signal-1      | Traceback (most recent call last):
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 577, in ensure_joined
matrix-bridge-signal-1      |     await self.join_room(room_id, max_retries=0)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 127, in wrapper
matrix-bridge-signal-1      |     return await __method(*args, **kwargs)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/client/store_updater.py", line 62, in join_room
matrix-bridge-signal-1      |     room_id = await super().join_room(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/client/api/rooms.py", line 326, in join_room
matrix-bridge-signal-1      |     content = await self.api.request(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 401, in request
matrix-bridge-signal-1      |     resp_data, resp = await self._send(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 256, in _send
matrix-bridge-signal-1      |     raise make_request_error(
matrix-bridge-signal-1      | mautrix.errors.request.MForbidden: You are not invited to this room.
matrix-bridge-signal-1      |
matrix-bridge-signal-1      | During handling of the above exception, another exception occurred:
matrix-bridge-signal-1      |
matrix-bridge-signal-1      | Traceback (most recent call last):
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 577, in ensure_joined
matrix-bridge-signal-1      |     await self.join_room(room_id, max_retries=0)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 127, in wrapper
matrix-bridge-signal-1      |     return await __method(*args, **kwargs)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/client/store_updater.py", line 62, in join_room
matrix-bridge-signal-1      |     room_id = await super().join_room(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/client/api/rooms.py", line 326, in join_room
matrix-bridge-signal-1      |     content = await self.api.request(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 401, in request
matrix-bridge-signal-1      |     resp_data, resp = await self._send(
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 256, in _send
matrix-bridge-signal-1      |     raise make_request_error(
matrix-bridge-signal-1      | mautrix.errors.request.MForbidden: You are not invited to this room.
matrix-bridge-signal-1      |
matrix-bridge-signal-1      | The above exception was the direct cause of the following exception:
matrix-bridge-signal-1      |
matrix-bridge-signal-1      | Traceback (most recent call last):
matrix-bridge-signal-1      |   File "/opt/mautrix-signal/mausignald/signald.py", line 82, in _run_event_handler
matrix-bridge-signal-1      |     await handler(event)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix_signal/signal.py", line 79, in on_message
matrix-bridge-signal-1      |     await self.handle_message(user, sender, evt.data_message)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix_signal/signal.py", line 184, in handle_message
matrix-bridge-signal-1      |     await self._handle_message(user, sender, msg, addr_override)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix_signal/signal.py", line 266, in _handle_message
matrix-bridge-signal-1      |     await portal.handle_signal_message(user, sender, msg)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 1165, in handle_signal_message
matrix-bridge-signal-1      |     await intent.set_typing(self.mxid, False)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 412, in set_typing
matrix-bridge-signal-1      |     await self.ensure_joined(room_id)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 583, in ensure_joined
matrix-bridge-signal-1      |     await bot.invite_user(room_id, self.mxid)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 140, in wrapper
matrix-bridge-signal-1      |     await __self.ensure_joined(room_id)
matrix-bridge-signal-1      |   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 581, in ensure_joined
matrix-bridge-signal-1      |     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
matrix-bridge-signal-1      | mautrix.errors.base.IntentError: Failed to join room !{{ROOM ID WAS HERE}}:matrix.at.alexmaras.com as @signalbot:matrix.at.alexmaras.com
```

**Comment by alexmaras** [comment]
Interestingly, I've signed out the other person from the signal bridge, and I'm still failing to receive messages in the signal chat. The same error comes through: `mautrix.errors.base.IntentError: Failed to join room !{ROOM ID WAS HERE}:matrix.at.alexmaras.com as @signalbot:matrix.at.alexmaras.com`

**Comment by jakecoppinger** [comment]
Not a maintainer so I can't fix it, but to clarify:

 - is this a Signal DM between the two double puppetted users or in a group chat they both participate in?
- do you know the version where this starts happening if it's a regression? (ie. Do I hold off updating my server 😀)

**Comment by alexmaras** [comment]
@jakecoppinger 
- it's a DM, group chats with the same user are working fine. This makes some sense to me - the signal bot is in the group chat, but is not in the DM
- This is the latest version of the bridge from the `dock.mau.dev/mautrix/signal` docker image, but this has been happening a little more than a week I think? I can't pin down exactly when it started I'm afraid.
