### ISSUE TITLE
Register error

### ISSUE THREAD

**Issue by NijremNL** [mautrix/signal#312]

**Comment by NijremNL** [comment]
I used the command ‘Register …’ but i got this error:
Unhandled error while handling command. Check logs for more details (ref: 1663748814).

**Comment by aHcVolle** [comment]
Got the same problem, this seems to be the log of signald, so i guess this is not related to the bridge:

`18:38:06.078 [0c64460b-905d-49dc-939d-fbce38ac94cb-register] INFO  io.finn.signald.RegistrationManager - Created a registration manager for [redacted 10]477
18:38:09.474 [0c64460b-905d-49dc-939d-fbce38ac94cb-register] ERROR register - error while handling request
java.lang.InternalError: error registering with server
	at io.finn.signald.clientprotocol.v1.RegisterRequest.run(RegisterRequest.java:58) ~[signald.jar:?]
	at io.finn.signald.clientprotocol.v1.RegisterRequest.run(RegisterRequest.java:28) ~[signald.jar:?]
	at io.finn.signald.clientprotocol.Request.<init>(Request.java:146) ~[signald.jar:?]
	at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) ~[signald.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.whispersystems.signalservice.api.push.exceptions.RateLimitException: [413] Rate limit exceeded: 413
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1754) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1735) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1717) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1706) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1642) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1630) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestSmsVerificationCode(PushServiceSocket.java:319) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:248) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_50_signald_1.jar:?]
	at io.finn.signald.RegistrationManager.register(RegistrationManager.java:87) ~[signald.jar:?]
	at io.finn.signald.clientprotocol.v1.RegisterRequest.run(RegisterRequest.java:54) ~[signald.jar:?]
`

**Comment by thefinn93** [comment]
@aHcVolle looks like the server is rate-limiting you.

**Comment by aHcVolle** [comment]
Yeah,  i thought taht too but:

- i get the rate limiting message when regustering via mautrix-signal
- i also get the rate limiting message when trying to register in an android emulator (android 12 x86_64)
- i can register with my phone 
 All tries share the same phone number an are logged in via the same WAN connection so i thought this might be some kind of invalid registration ....

**Comment by thefinn93** [comment]
when the Signal app has access to FCM it can send a some kind of token when registering. They probably rate limit more "real" looking devices (ie. ones with FCM tokens) less heavily.
