### ISSUE TITLE
pm PHONE throws AttributeError

### ISSUE THREAD

**Issue by felixx9** [mautrix/signal#319]
sending `pm <phone>` to the bridge is throwing me an AttributeError.
My signal app ist up to date. **Stories** are a new "Feature". Anything to do with this?

Not sure, whether it also could be a signald issue?

`AttributeError: 'NoneType' object has no attribute 'number'`

```
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]: [2022-11-08 09:54:25,136] [ERROR@mau.commands] Unhandled error while handling command pm <PHONE> from <MATRIX-ID> (ref: 1667866371)
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]: Traceback (most recent call last):
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:     await self._run_handler(handler, evt)
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:     return await self._handler(evt)
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:   File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 105, in pm
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:     puppet = await _get_puppet_from_cmd(evt)
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:   File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 66, in _get_puppet_from_cmd
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]:     uuid = await evt.bridge.signal.find_uuid(evt.sender.username, puppet.number)
Nov 08 09:54:25 <HOSTNAME> matrix-mautrix-signal[4115]: AttributeError: 'NoneType' object has no attribute 'number'
```

**Comment by tulir** [comment]
This was fixed already

**Comment by felixx9** [comment]
oh sorry!!!

**Comment by felixx9** [comment]
970c75506cd4e91a7d12fc0d3841d1ef3b79051c
