### ISSUE TITLE
send image doesnt work when the bridge is running with umask 027

### ISSUE THREAD

**Issue by emdete** [mautrix/signal#322]
on my server `umask 0277` is standard. i was never able to send images to signal users (while telegram worked). excception was 

```
[2022-11-20 10:54:17,655] [ERROR@mau.portal.ec152880-48bd-4891-bdde-824bbee056ce] Failed to handle Matrix message $eAneq0HFzFF1vCHMFUWdEtN4Uagh1_Fp_m0e-vp8dYs
Traceback (most recent call last):
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mautrix_signal/portal.py", line 311, in handle_matrix_message
    await self._handle_matrix_message(sender, message, event_id)
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mautrix_signal/portal.py", line 480, in _handle_matrix_message
    retry_count = await self._signal_send_with_retries(
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mautrix_signal/portal.py", line 547, in _signal_send_with_retries
    await send_fn(sender, event_id, req_id=req_id, **send_args)
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mausignald/signald.py", line 261, in send
    resp = await self.send_raw(
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mausignald/signald.py", line 235, in send_raw
    resp = await self.request_v1(
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/home/mautrix-signal/env/lib/python3.10/site-packages/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: java.io.FileNotFoundException: java.io.FileNotFoundException: /tmp/mautrix-signal-4ebfcf7f-c1cb-4851-92aa-bd3600adbcf5 (Permission denied)
```

the file has permission `-rw-r-----`. 

changing the startup to `umask 022` solves the isssue. dont know how telegram handles that (with signal there is an additional daemon and user). maybe only group needs to be added? i didnt find docs about that.

**Comment by TCCQ** [comment]
I am having a similar issue. No pictures are bridged from signal to matrix. I am running outside of docker with systemd units and different users. The signald unit reports no problems in the log, but the mautrix-signal unit reports
```
Sep 06 10:26:44 CnOServer python[3701]: Traceback (most recent call last):
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mausignald/signald.py", line 84, in _run_event_handler
Sep 06 10:26:44 CnOServer python[3701]:     await handler(event)
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/signal.py", line 84, in on_message
Sep 06 10:26:44 CnOServer python[3701]:     await self.handle_message(user, sender, evt.data_message)
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/signal.py", line 207, in handle_message
Sep 06 10:26:44 CnOServer python[3701]:     await self._handle_message(user, sender, msg, addr_override)
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/signal.py", line 285, in _handle_message
Sep 06 10:26:44 CnOServer python[3701]:     await portal.handle_signal_message(user, sender, msg)
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/portal.py", line 1279, in handle_signal_message
Sep 06 10:26:44 CnOServer python[3701]:     content = await self._handle_signal_attachment(intent, attachment, text=as_text)
Sep 06 10:26:44 CnOServer python[3701]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 06 10:26:44 CnOServer python[3701]:   File "/opt/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/portal.py", line 1638, in _handle_signal_attachment
Sep 06 10:26:44 CnOServer python[3701]:     os.remove(attachment.incoming_filename)
Sep 06 10:26:44 CnOServer python[3701]: PermissionError: [Errno 13] Permission denied: '/var/lib/signald/attachments/-kQpvTiryE5pjcmZ5Pe1'
```

The file exists, and it and all parent directories have read/execute permissions for either everyone or the signald group:
```
-rw-rw---- 1 signald signald 326917 Sep  6 10:26 /var/lib/signald/attachments/-kQpvTiryE5pjcmZ5Pe1
```

and the mautrix-signal user is in the signald group.

Am I blind? I'm not using any other bridges, and none would be terribly convenient to set up, so I don't know if this is signal specific. Thoughts?

**Comment by TCCQ** [comment]
Oh I am dumb. It needs write to delete files. I was getting a read error before I fixed that.
