### ISSUE TITLE
problems with pm and create commands

### ISSUE THREAD

**Issue by skornhuber** [mautrix/signal#328]
we have set up our homeserver and everything is going well, also the bridges - thanks a lot for you efforts.

However i get some issues by using commands over the signal bridge (python installation) - (at the whatsapp bridge everything is working well including the commands)

version mautrix-signal
[0.4.2]

command and results including logs for pm and create command as follows

using pm
*********
message to bot: pm +xxxxxxxxx
reply of bot: Usage: pm <phone> (enter phone number in international format)

```
[2022-12-05 09:59:34,219] [INFO@aiohttp.access] 127.0.0.1 [05/Dec/2022:08:59:34 +0000] "PUT /transactions/2103?access_token=yyyy HTTP/1.1" 200 158 "-" "Synapse/1.72.0"
[2022-12-05 09:59:34,219] [DEBUG@mau.mx] Received Matrix event $zzzz from @bbbb:xxx.xxx in aaaa:xxx.xxx
[2022-12-05 09:59:34,403] [DEBUG@mau.as.api.bot] req #565: GET https://ffff/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/joined_members?user_id=@signalbot:xxx.xxx None
[2022-12-05 09:59:34,410] [DEBUG@mau.as.api.bot] req #565 (/v3/rooms/%21aaaa%3Axxx.xxx/joined_members) completed in 6.4ms with status 200
[2022-12-05 09:59:34,417] [DEBUG@mau.as.api.bot] req #566: PUT https://ffff/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/send/m.room.message/mautrix-python_vvvv?user_id=@signalbot:xxx.xxx {"msgtype": "m.notice", "body": "**Usage:** `pm <phone>` (enter phone number in international format)", "format": "org.matrix.custom.html", "formatted_body": "<p><strong>Usage:</strong> <code>pm &lt;phone&gt;</code> (enter phone number in international format)</p>\n"}
```

using create
************
message to bot: create test
reply of bot: Unhandled error while handling command. Check logs for more details (ref: 1670150361).

```
[2022-12-05 10:01:14,703] [INFO@aiohttp.access] 127.0.0.1 [05/Dec/2022:09:01:14 +0000] "PUT /transactions/2110?access_token=xxxx HTTP/1.1" 200 158 "-" "Synapse/1.72.0"
[2022-12-05 10:01:14,704] [DEBUG@mau.mx] Received Matrix event $wwww from @xxx:xxx.xxx in !xxx:xxx.xxx
[2022-12-05 10:01:14,706] [DEBUG@mau.as.api.bot] req #567: GET http://127.0.01:8008/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/joined_members?user_id=@signalbot:xxx.xxx None
[2022-12-05 10:01:14,712] [DEBUG@mau.as.api.bot] req #567 (/v3/rooms/%21aaaa%3Axxx.xxx/joined_members) completed in 6.0ms with status 200
[2022-12-05 10:01:14,716] [DEBUG@mau.as.api.bot] req #568: GET http://127.0.01:8008/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/state?user_id=@signalbot:xxx.xxx None
[2022-12-05 10:01:14,724] [DEBUG@mau.as.api.bot] req #568 (/v3/rooms/%21aaaa%3Axxx.xxx/state) completed in 8.3ms with status 200
[2022-12-05 10:01:14,739] [DEBUG@mau.as.api.bot] req #569: GET http://127.0.01:8008/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/members?user_id=@signalbot:xxx.xxx None
[2022-12-05 10:01:14,753] [DEBUG@mau.as.api.bot] req #569 (/v3/rooms/%21aaaa%3Axxx.xxx/members) completed in 12.9ms with status 200
[2022-12-05 10:01:14,933] [DEBUG@mausignald] Request uuuu: create_group
[2022-12-05 10:01:14,936] [ERROR@mau.commands] Unhandled error while handling command create test from @bbbb:xxx.xxx (ref: 1670150361)
Traceback (most recent call last):
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/commands/signal.py", line 356, in create
    await portal.create_signal_group(evt.sender, levels, join_rule)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/portal.py", line 1787, in create_signal_group
    signal_chat = await self.signal.create_group(
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mausignald/signald.py", line 439, in create_group
    resp = await self.request_v1("create_group", account=username, **create_params)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/srv/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.RequestValidationFailure: missing required argument: title
[2022-12-05 10:01:14,944] [DEBUG@mau.as.api.bot] req #570: PUT https://ffff/_matrix/client/v3/rooms/%21aaaa%3Axxx.xxx/send/m.room.message/mautrix-python_ttt?user_id=@signalbot:xxx.xxx {"msgtype": "m.notice", "body": "Unhandled error while handling command. Check logs for more details (ref: 1670150361).", "format": "org.matrix.custom.html", "formatted_body": "<p>Unhandled error while handling command. Check logs for more details (ref: 1670150361).</p>\n"}
[2022-12-05 10:01:14,977] [DEBUG@mau.as.api.bot] req #570 (/v3/rooms/%21aaaa%3Axxx.xxx/send/m.room.message/mautrix-python_ttt) completed in 32.3ms with status 200
[2022-12-05 10:01:14,978] [DEBUG@mau.mx] Error handling command create from User(mxid='@bbbb:xxx.xxx', username='+ssss', uuid=UUID('rrrr'), notice_room='aaaa:xxx.xxx'): missing required argument: title
```

**Comment by survirtual** [comment]
This might be related to an SGX error on intel devices on signald: https://gitlab.com/signald/signald/-/issues/345 -- at least, I experienced this problem as well and this was the reason. 

Also, it was connected to the bridge being a primary device.  I decided to experiment as a secondary.  Instead of being a primary, I logged out, then I installed signal on a Android VM using Android Studio.  You can use any android device you want, but if you don't have one handy, a VM + an available phone number works fine.  You can look up how to use Android Studio to make an android virtual device anywhere.

I then linked that primary Signal device using the bridge, with the bridge as a secondary.  This solved the issue for me.

**Comment by skornhuber** [comment]
Yes it is an intel device
okay, thanks for explanation - I will use in the meantime the workaround via the cell phone client

**Comment by skornhuber** [comment]
sorry, I discribed my commands above in the original text
for creating the room
I used create <name>
e.g. create test
so room name is set

for pm
I used more a less copy & paste from whatsapp bridge - at whatsapp bridge it is working on signal bridge it is not working
there was no extra character.

**Comment by tulir** [comment]
The create command doesn't take any parameters, you just need to set the room name before running the command.

**Comment by skornhuber** [comment]
> The create command doesn't take any parameters, you just need to set the room name before running the command.
sorry I missinterpreted the docu - create first matrixroom, invite signal bot - create command and it is working - thanks!
