### ISSUE TITLE
Failing to register new bridge

### ISSUE THREAD

**Issue by bvbore** [mautrix/signal#346]
I initially setup a matrix server using conduit to test viability, but I'm moving over to synapse now for a more permanent setup.  I setup mautrix-signal as the primary device on conduit, and am trying to setup a **new** bridge to take over and connect to synapse instead.

The bridge is connected and responding, I use the register command with a captcha to trigger an SMS code being sent to my phone, which I enter and then get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 219, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 171, in verify
    resp = await self.request_v1("verify", account=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 245, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 239, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 236, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: AccountAlreadyVerifiedError: account has already been verified
```

After waiting for the rate limit to cool down I have also occasionally seen
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 219, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 171, in verify
    resp = await self.request_v1("verify", account=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 245, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 239, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 236, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [401] Authorization failed!
```

I am running everything in containers.

**Comment by bvbore** [comment]
connect-existing worked for me.  https://gitlab.com/signald/signald/-/issues/351#note_1278715532

**Comment by WhiteTomX** [comment]
I think I got the same Problem @bvbore. Can you elaborate what you did? I can't find a solution in the linked comment or issue.

**Comment by Thatoo** [comment]
Apparently there is nothing we can do except hoping for a fix in next signald version. The problem occu after v 0.23.0
