### ISSUE TITLE
Some of the brand new E2(B)E key-removal options errors on message send

### ISSUE THREAD

**Issue by olmari** [mautrix/signal#355]
When sending a message to signal contact, bridge used as primary device if that matters, mautrix-signal fails with error and doesn't deliver. I'm not sure yet which setting it is, but here is log and config snippet what I've tried to deploy:

```
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]: [2023-04-13 22:56:39,691] [DEBUG@mau.crypto] Ratchet safety info for <redacted_string>: RatchetSafety(next_index=3, missed_indices=[0, 1], lost_indices=[]), ratchet_target_index=0
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]: [2023-04-13 22:56:39,691] [ERROR@mau.as] Exception in Matrix event handler
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]: Traceback (most recent call last):
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/appservice/as_handler.py", line 312, in try_handle
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     await handler_func(event)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 1026, in int_handle_event
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     await self.handle_encrypted(evt)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 799, in handle_encrypted
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     decrypted = await self.e2ee.decrypt(evt, wait_session_timeout=3)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/bridge/e2ee.py", line 224, in decrypt
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     decrypted = await self.crypto.decrypt_megolm_event(evt)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/crypto/decrypt_megolm.py", line 64, in decrypt_megolm_event
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     await self._ratchet_session(session, index)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/crypto/decrypt_megolm.py", line 192, in _ratchet_session
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     await self.crypto_store.put_group_session(sess.room_id, sess.sender_key, sess_id, sess)
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:   File "/opt/signalbot/lib/python3.9/site-packages/mautrix/crypto/store/asyncpg/store.py", line 260, in put_group_session
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]:     int(session.max_age.total_seconds() * 1000),
Apr 13 22:56:39 morpheus.hacklab.fi python[446360]: AttributeError: 'NoneType' object has no attribute 'total_seconds'
```

```
    # End-to-bridge encryption support options.
    #
    # See https://docs.mau.fi/bridges/general/end-to-bridge-encryption.html for more info.
    encryption:
        # Allow encryption, work in group chat rooms with e2ee enabled
        allow: true
        # Default to encryption, force-enable encryption in all portals the bridge creates
        # This will cause the bridge bot to be in private chats for the encryption to work properly.
        default: true
        # Whether to use MSC2409/MSC3202 instead of /sync long polling for receiving encryption-related data.
        appservice: false
        # Require encryption, drop any unencrypted messages.
        require: false
        # Enable key sharing? If enabled, key requests for rooms where users are in will be fulfilled.
        # You must use a client that supports requesting keys from other users to use this feature.
        allow_key_sharing: false
        # Options for deleting megolm sessions from the bridge.
        delete_keys:
            # Beeper-specific: delete outbound sessions when hungryserv confirms
            # that the user has uploaded the key to key backup.
            delete_outbound_on_ack: false
            # Don't store outbound sessions in the inbound table.
            dont_store_outbound: true
            # Ratchet megolm sessions forward after decrypting messages.
            ratchet_on_decrypt: true
            # Delete fully used keys (index >= max_messages) after decrypting messages.
            delete_fully_used_on_decrypt: true
            # Delete previous megolm sessions from same device when receiving a new one.
            delete_prev_on_new_session: true
            # Delete megolm sessions received from a device when the device is deleted.
            delete_on_device_delete: true
            # Periodically delete megolm sessions when 2x max_age has passed since receiving the session.
            periodically_delete_expired: true
        # What level of device verification should be required from users?
        #
        # Valid levels:
        #   unverified - Send keys to all device in the room.
        #   cross-signed-untrusted - Require valid cross-signing, but trust all cross-signing keys.
        #   cross-signed-tofu - Require valid cross-signing, trust cross-signing keys on first use (and reject changes).
        #   cross-signed-verified - Require valid cross-signing, plus a valid user signature from the bridge bot.
        #                           Note that creating user signatures from the bridge bot is not currently possible.
        #   verified - Require manual per-device verification
        #              (currently only possible by modifying the `trust` column in the `crypto_device` database table).
        verification_levels:
            # Minimum level for which the bridge should send keys to when bridging messages from Telegram to Matrix.
            receive: unverified
            # Minimum level that the bridge should accept for incoming Matrix messages.
            send: unverified
            # Minimum level that the bridge should require for accepting key requests.
            share: cross-signed-tofu
        # Options for Megolm room key rotation. These options allow you to
        # configure the m.room.encryption event content. See:
        # https://spec.matrix.org/v1.3/client-server-api/#mroomencryption for
        # more information about that event.
        rotation:
            # Enable custom Megolm room key rotation settings. Note that these
            # settings will only apply to rooms created after this option is
            # set.
            enable_custom: false
            # The maximum number of milliseconds a session should be used
            # before changing it. The Matrix spec recommends 604800000 (a week)
            # as the default.
            milliseconds: 604800000
            # The maximum number of messages that should be sent with a given a
            # session before changing it. The Matrix spec recommends 100 as the
            # default.
            messages: 100
```

**Comment by olmari** [comment]
Hmm... I do get same error now even when I set every option to false, so it's not directly any setting used or not.

**Comment by olmari** [comment]
After setting everything to false again, same error still comes up with the original person I was testing it with, but no error on another one and looks like successful send.

**Comment by olmari** [comment]
Tried settings one by one with new contact with restarting bridge on every change and even after all related settings again true, it did not break... Issuing an `/discardsession' with the erroring one did seem to help.. I don't know was this one time fluke or what, but.. meh :)
