### ISSUE TITLE
Power level bug with dendrite

### ISSUE THREAD

**Issue by ibeckermayer** [mautrix/signal#357]
I'm attempting to run this bridge alongside dendrite (via https://github.com/spantaleev/matrix-docker-ansible-deploy), and am running into a bug I haven't been able to find anywhere online. 

Everything appears to be running fine initially, but when I start a new chat with the bot, the room becomes entitled `Empty room (was Signal bridge bot)`. I can still see both users in the room in the interface, but the bridge bot won't respond to me.

<details>
<summary>Screenshot</summary>
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/13578537/232274801-9c6d9b40-a277-427c-a196-adad4836510d.png">
</details>

When I look at mautrix signal logs, I see a bunch of this type of error

<details>
<summary>Mautrix Signal Logs</summary>

```
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]: [2023-04-16 05:57:24,885] [ERROR@mau.as] Exception in Matrix event handler
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]: Traceback (most recent call last):
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 311, in try_handle
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await handler_func(event)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 949, in int_handle_event
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await self.int_handle_invite(evt)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 534, in int_handle_invite
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await self.accept_bot_invite(evt.room_id, inviter)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 498, in accept_bot_invite
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await self.send_welcome_message(room_id, inviter)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix_signal/matrix.py", line 74, in send_welcome_message
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await super().send_welcome_message(room_id, inviter)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 525, in send_welcome_message
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await self.az.intent.send_notice(room_id, text=combined, html=combined_html)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/client/api/events.py", line 525, in send_text
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     return await self.send_message(room_id, content, **kwargs)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 141, in wrapper
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     return await __method(*args, **kwargs)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 428, in send_message_event
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     await self._ensure_has_power_level_for(room_id, event_type)
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:   File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 646, in _ensure_has_power_level_for
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]:     raise IntentError(
Apr 16 05:57:24 hermetic matrix-mautrix-signal[51797]: mautrix.errors.base.IntentError: Power level of @signalbot:hermetic.chat is not enough for m.room.message in !IixJ0ZrHAAyreG72:hermetic.chat
```
</details>

suggesting that the bot doesn't have a power level necessary for sending messages to this room. However, I can see in the interface that the bot has a power level of 100

<details>
<summary>Screenshot</summary>
<img width="528" alt="image" src="https://user-images.githubusercontent.com/13578537/232275064-6dd7620b-aff8-4a6b-b7aa-668a6f1ff240.png">
</details>

whereas the limit in the room to send messages is set to 0
<details>
<summary>Screenshot</summary>
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/13578537/232275132-eb032a88-a9eb-4340-8a44-664167bcb31a.png">
</details>

Dendrite logs are a little cryptic, although the sequence of events does seem a bit odd:
<details>
<summary>Dendrite Logs</summary>

```
Apr 16 05:57:23 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:23.967150878Z" level=info msg="Creating new room" req.id=Jway2o35y35O req.method=POST req.path=/_matrix/client/r0/createRoom roomID="!IixJ0ZrHAAyreG72:hermetic.chat" roomVersion=10 userID="@isaiah:hermetic.chat" user_id="@isaiah:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.391825786Z" level=info msg="User requested to room join" room_id="!IixJ0ZrHAAyreG72:hermetic.chat" servers="[]" user_id="@signalbot:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.392469227Z" level=info msg="User requested to room join" room_id="!IixJ0ZrHAAyreG72:hermetic.chat" servers="[]" user_id="@signalbot:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.460759518Z" level=info msg="Fetched 1 events locally" backwards=true end="" req.id=unZolx9q0sMS req.method=GET req.path="/_matrix/client/r0/rooms/!IixJ0ZrHAAyreG72:hermetic.chat/messages" start=t1_199 user_id="@isaiah:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.473907465Z" level=info msg="User joined room successfully" room_id="!IixJ0ZrHAAyreG72:hermetic.chat" servers="[]" user_id="@signalbot:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.489531291Z" level=info msg=Responding backwards=true from=t1_199 limit=20 req.id=unZolx9q0sMS req.method=GET req.path="/_matrix/client/r0/rooms/!IixJ0ZrHAAyreG72:hermetic.chat/messages" return_end="" return_start=t1_199 to="" user_id="@isaiah:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.532888476Z" level=warning msg="State reset detected (removing 1 events)" event_id="$r7b6xLJ77hSL9ehtPtjXeDFC7uRlKMbtq51M5g0Az70" new_latest="[$r7b6xLJ77hSL9ehtPtjXeDFC7uRlKMbtq51M5g0Az70 $K27A3qsU2-X7vowq74Uy9QUesg0GE4MV6b_WnAXcI3Q]" new_state_nid=290 old_latest="[$K27A3qsU2-X7vowq74Uy9QUesg0GE4MV6b_WnAXcI3Q]" old_state_nid=288 room_id="!IixJ0ZrHAAyreG72:hermetic.chat"
Apr 16 05:57:24 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:24.560210900Z" level=info msg="User joined room successfully" room_id="!IixJ0ZrHAAyreG72:hermetic.chat" servers="[]" user_id="@signalbot:hermetic.chat"
Apr 16 05:57:29 hermetic matrix-dendrite[49001]: time="2023-04-16T05:57:29.446905379Z" level=info msg="Sent event to roomserver" event_id="$s0Xg3EIliol_AHrByljWp-MBj_RitE789H7G1WVOMI8" req.id=rm3vgazOgVtL req.method=PUT req.path="/_matrix/client/r0/rooms/!IixJ0ZrHAAyreG72:hermetic.chat/send/m.room.message/m1681624649338.8" room_id="!IixJ0ZrHAAyreG72:hermetic.chat" room_version=10 user_id="@isaiah:hermetic.chat"
```

</details>

**Comment by tulir** [comment]
Dendrite has some state bugs currently

**Comment by ibeckermayer** [comment]
Got it, for anybody running into a similar problem see the Dendrite issue here: https://github.com/matrix-org/dendrite/issues/2902

**Comment by S7evinK** [comment]
One issue in Dendrite was that we would send the invite event twice to the bot, which would then join twice, resulting in the logs above (duplicate join, resulting in a state reset..)
Duplicate invites should be [fixed](https://github.com/matrix-org/dendrite/pull/3020), as well as the [state reset](https://github.com/matrix-org/dendrite/pull/3040) in those cases.
