### ISSUE TITLE
`!signal create` leads to an exception

### ISSUE THREAD

**Issue by weeman1337** [mautrix/signal#361]
- Create a matrix room
- Invite the bridge bot
- Send `!signal create`

Expected result: It should create a Signal chat

What happens: Exception
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 356, in create
    await portal.create_signal_group(evt.sender, levels, join_rule)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 1787, in create_signal_group
    signal_chat = await self.signal.create_group(
  File "/opt/mautrix-signal/mausignald/signald.py", line 439, in create_group
    resp = await self.request_v1("create_group", account=username, **create_params)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found

```

**Comment by kuba-orlik** [comment]
I'm also getting an exception, but with a different message: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 356, in create
    await portal.create_signal_group(evt.sender, levels, join_rule)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 1787, in create_signal_group
    signal_chat = await self.signal.create_group(
  File "/opt/mautrix-signal/mausignald/signald.py", line 439, in create_group
    resp = await self.request_v1("create_group", account=username, **create_params)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: NullPointerException: no message, see signald logs
```

**Comment by PascalBru** [comment]
@kuba-orlik Which build are you using? Have the same problem with the latest docker image

**Comment by floviolleau** [comment]
Hi,

Maybe linked to #364?

**Comment by m-bers** [comment]
Getting the same error in `mautrix-signal`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 370, in create
    await portal.create_signal_group(evt.sender, levels, join_rule)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 1856, in create_signal_group
    signal_chat = await self.signal.create_group(
  File "/opt/mautrix-signal/mausignald/signald.py", line 485, in create_group
    resp = await self.request_v1("create_group", account=username, **create_params)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 245, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 239, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 236, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: NullPointerException: no message, see signald logs
```

And in signald logs here is the corresponding error:


```
07:27:05.546 [1dd3c315-3d1d-4a5e-8c51-238489f9359e-get_profile] INFO  get_profile - handled request 1dd3c315-3d1d-4a5e-8c51-238489f9359e successfully
07:27:14.926 [ef5a367e-30bc-4064-aee1-676280d185e4-create_group] ERROR create_group - error while handling request
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
        at java.util.Optional.of(Unknown Source) ~[?:?]
        at io.finn.signald.Groups.createGroup(Groups.java:360) ~[signald.jar:?]
        at io.finn.signald.clientprotocol.v1.CreateGroupRequest.run(CreateGroupRequest.java:106) ~[signald.jar:?]
        at io.finn.signald.clientprotocol.v1.CreateGroupRequest.run(CreateGroupRequest.java:41) ~[signald.jar:?]
        at io.finn.signald.clientprotocol.Request.<init>(Request.java:146) ~[signald.jar:?]
        at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) ~[signald.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

I'm using `dock.mau.dev/mautrix/signal:latest`

**Comment by Kuchenmampfer** [comment]
I also get the original exception using the version 0.23.2 via the ansible playbooks docker container.
And trying to pm someone by phone number also throws this exception for me.

**Comment by madduck** [comment]
I get the same exception when trying to `pm`. Using 1.4.3 from pip, and signald 0.23.2-7-1583b4df
