### ISSUE TITLE
SQLite Error with new instance

### ISSUE THREAD

**Issue by Cebrain** [mautrix/signal#366]
Hey,
i tried to install mautrix-signal with a SQLite Database.
As i see there is something wrong when it tries to create the database:

```
[2023-05-30 11:19:42,448] [INFO@mau.init] Initializing mautrix-signal 0.4.3
[2023-05-30 11:19:42,450] [INFO@mau.init] Initialization complete in 0.08 seconds
[2023-05-30 11:19:42,450] [DEBUG@mau.init] Running startup actions...
[2023-05-30 11:19:42,450] [DEBUG@mau.init] Starting database...
[2023-05-30 11:19:42,450] [DEBUG@mau.db] Connecting to sqlite:/filename1.db
[2023-05-30 11:19:42,450] [DEBUG@mau.db] Database connection init commands: ['PRAGMA foreign_keys = ON', 'PRAGMA journal_mode = WAL', 'PRAGMA busy_timeout = 5000']
[2023-05-30 11:19:42,451] [CRITICAL@mau.init] Failed to initialize database
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 215, in start_db
    await self.db.start()
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/aiosqlite.py", line 154, in start
    conn = await TxnConnection(self._path, **self._db_args)
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect
    self._connection = await future
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/aiosqlite.py", line 29, in connector
    return sqlite3.connect(
sqlite3.OperationalError: unable to open database file
[2023-05-30 11:19:42,451] [DEBUG@mau.init] Stopping database due to SystemExit
[2023-05-30 11:19:42,451] [DEBUG@mau.init] Database stopped
```

**Comment by tulir** [comment]
That usually happens if the path isn't writable (e.g. missing permissions, directory not existing or wrong path in general)

(also, github issues are not for debugging setup issues)

**Comment by arapov** [comment]
I gave maturix-signal a shot today and hit this issue, I think. I am using mautrix-telegram for some time already, which has similar configuration file.

you can see that sqlite db file is pointed to /data/ directory which is mapped from the host system. mautrix-signal has no problems creating config and registration yamls there, so it is writable.

@tulir, any good hint?

```
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,292] [DEBUG@mau.init] Database stopped
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,292] [DEBUG@mau.init] Stopping database due to SystemExit
Jul 18 08:42:36 harbard mautrix-signal[996269]: sqlite3.OperationalError: unable to open database file
Jul 18 08:42:36 harbard mautrix-signal[996269]:     return sqlite3.connect(
Jul 18 08:42:36 harbard mautrix-signal[996269]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/aiosqlite.py", line 29, in connector
Jul 18 08:42:36 harbard mautrix-signal[996269]:     result = function()
Jul 18 08:42:36 harbard mautrix-signal[996269]:   File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
Jul 18 08:42:36 harbard mautrix-signal[996269]:     self._connection = await future
Jul 18 08:42:36 harbard mautrix-signal[996269]:   File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect
Jul 18 08:42:36 harbard mautrix-signal[996269]:     conn = await TxnConnection(self._path, **self._db_args)
Jul 18 08:42:36 harbard mautrix-signal[996269]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/aiosqlite.py", line 154, in start
Jul 18 08:42:36 harbard mautrix-signal[996269]:     await self.db.start()
Jul 18 08:42:36 harbard mautrix-signal[996269]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 215, in start_db
Jul 18 08:42:36 harbard mautrix-signal[996269]: Traceback (most recent call last):
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,289] [CRITICAL@mau.init] Failed to initialize database
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,288] [DEBUG@mau.db] Database connection init commands: ['PRAGMA foreign_keys = ON', 'PRAGMA journal_>
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,287] [DEBUG@mau.db] Connecting to sqlite:/data/mautrix-signal.db
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,287] [DEBUG@mau.init] Starting database...
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,287] [DEBUG@mau.init] Running startup actions...
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,286] [INFO@mau.init] Initialization complete in 0.37 seconds
Jul 18 08:42:36 harbard mautrix-signal[996269]: [2023-07-18 06:42:36,278] [INFO@mau.init] Initializing mautrix-signal 0.4.3
```

**Comment by arapov** [comment]
I got it working, by using 4(four) slashes in conn line, i.e. `sqlite:////data/file.db`
