### ISSUE TITLE
Cannot reconnect with 'connect-existing'

### ISSUE THREAD

**Issue by Wyrrrd** [mautrix/signal#369]
I lost my connection to mautrix-signal and cannot reconnect. 'register' tells me I am already registered, 'connect-existing' does not accept my phone number. When I am trying any notation besides E.164, it reminds me to use exactly this notation. When I use it, I get a NOT_A_NUMBER error from phonenumberutil.

I am hosting this via [docker](https://docs.mau.fi/bridges/python/signal/docker-setup.html).

<details>
<summary>Error log</summary>

```
[2023-07-03 11:33:13,641] [DEBUG@mau.as.api.bot] req #93: PUT http://XXXXXX:8008/_matrix/client/v3/rooms/XXXXXX/send/m.room.message/mautrix-python_1688383993641114441_7?user_id=@signalbot:gammag.de {"msgtype": "m.notice", "body": "Please enter the phone number in international format (E.164)", "format": "org.matrix.custom.html", "formatted_body": "<p>Please enter the phone number in international format (E.164)</p>\n"}

[...]

[2023-07-03 11:33:20,187] [ERROR@mau.commands] Unhandled error while handling command Connect-existing +XXXXXX from @wyrrrd:XXXXXX (ref: 1688383214)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 89, in connect_existing
    f"Successfully logged in as {pu.Puppet.fmt_phone(evt.sender.username)} "
  File "/usr/lib/python3.10/site-packages/mautrix_signal/puppet.py", line 248, in fmt_phone
    parsed = phonenumbers.parse(number)
  File "/usr/lib/python3.10/site-packages/phonenumbers/phonenumberutil.py", line 2912, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The phone number supplied was None.
```
</details>

**Comment by tulir** [comment]
That probably happens if the session isn't valid or subscribing with signald fails for some other reason, most likely requires relogin

**Comment by Wyrrrd** [comment]
What do you mean by relogin?

As registering didn't work as well, I manually deleted my account in signald (`signaldctl account delete +XXXXXX`), then ran into [signald#351](https://gitlab.com/signald/signald/-/issues/351), deleted and recreated it on version 0.23.0.

After all, registration worked finally, but I lost the messages received during my outage. `connect-existing` still seems to be broken on phone number parsing.
