### ISSUE TITLE
error registering with server

### ISSUE THREAD

**Issue by Thatoo** [mautrix/signal#371]
registration fail
In the signal bridge bot room, I launch the command : `register --captcha signal-hcaptcha.LONGSTRING phonenumber
`
I get the following error : `Unhadled error while handling command. Check logs for more details (ref: xxxx)`.
In the log, I found, linked to the ref : 

```
[2023-07-08 19:16:11,893] [ERROR@mau.commands] Unhandled error while handling command register +xxxxxxxxxxx from @zzz:mydomain.fr (ref: 1688749722)
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 180, in register
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/signald.py", line 160, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: error registering with server

```

**Comment by djmaze** [comment]
Same here when trying to register a landline number with `--voice`
