### ISSUE TITLE
Linking not posible

### ISSUE THREAD

**Issue by RudolfRakete** [mautrix/signal#375]
I installed the bridge (v0.4.3) following the [docker guide](https://docs.mau.fi/bridges/python/signal/docker-setup.html). 
The `link` command fails with the following error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 117, in link
    content = await make_qr(evt.az.intent, sess.uri)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/auth.py", line 52, in make_qr
    mxc = await intent.upload_media(qr, "image/png", "qr.png", len(qr))
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 128, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mautrix/client/api/modules/media_repository.py", line 165, in upload_media
    resp = await task
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 395, in request
    resp_data, resp = await self._send(
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 250, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: Internal server error
```
Can anyone figure out what's wrong?

**Comment by tulir** [comment]
That means your homeserver is broken (specifically the media repo)
