### ISSUE TITLE
Error starting: `pq: SSL is not enabled on the server`

### ISSUE THREAD

**Issue by raldone01** [mautrix/signal#383]
```
panic: failed to check if table exists: pq: SSL is not enabled on the server

goroutine 1 [running]:
go.mau.fi/util/dbutil.(*Database).tableExistsNoError(0xc000534470?, {0x153f140?, 0x0?})
 /builds/mautrix/signal/.cache/pkg/mod/go.mau.fi/util@v0.2.1/dbutil/upgrades.go:113 +0x73
go.mau.fi/util/dbutil.(*Database).checkDatabaseOwner(0xc000038600)
 /builds/mautrix/signal/.cache/pkg/mod/go.mau.fi/util@v0.2.1/dbutil/upgrades.go:128 +0x65
go.mau.fi/util/dbutil.(*Database).Upgrade(0xc000038600)
 /builds/mautrix/signal/.cache/pkg/mod/go.mau.fi/util@v0.2.1/dbutil/upgrades.go:162 +0x27
maunium.net/go/mautrix/bridge.(*Bridge).start(0xc000473900)
 /builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.2/bridge/bridge.go:613 +0x56
maunium.net/go/mautrix/bridge.(*Bridge).Main(0xc000473900)
 /builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.2/bridge/bridge.go:801 +0x619
main.main()
 /builds/mautrix/signal/main.go:309 +0x2d2
 ```
 
 The bridge ran fine for a long time.
 Three days ago it was fine.
 
 Today I noticed that it could not start up.

**Comment by tulir** [comment]
The postgres driver for Go requires explicitly disabling TLS with `?sslmode=disable` in the connection string

**Comment by raldone01** [comment]
Thanks that did it.
I am super confused.
No idea why it was working up until now.

**Comment by tulir** [comment]
The bridge was written in Python until now

**Comment by raldone01** [comment]
I noticed just ditched signald.
