### ISSUE TITLE
Running the bridge fails with Go panic

### ISSUE THREAD

**Issue by kolaente** [mautrix/signal#387]
Up until recently, the bridge worked fine. Now when I try to do anything (even just typing seems to crash it), there's this error in the logs:

```
matrix-bridge-signal-1  | 2023-12-19T18:13:48Z ERR Panic in Matrix event handler error="invalid memory address or nil pointer dereference" event_content="{\"type\":\"m.typing\",\"room_id\":\"!roooom-id:kolaente.de\",\"content\":{\"user_ids\":[\"@kolaente:kolaente.de\"]}}" stack="goroutine 39 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\nmaunium.net/go/mautrix/appservice.(*EventProcessor).recoverFunc(0xc00003eb40, {0x1474f60, 0xc000405520})\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.3-0.20231219134117-a27bf782f377/appservice/eventprocessor.go:93 +0xa8\npanic({0x142a320?, 0x1e9f7a0?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngo.mau.fi/mautrix-signal/pkg/signalmeow.sendContent({0x16d7a40, 0x1f4a0c0}, 0x0, {0xc0000b6360, 0x24}, 0x18c8348b11c, 0xc000318dc0, 0x0)\n\t/builds/mautrix/signal/pkg/signalmeow/sending.go:659 +0x140\ngo.mau.fi/mautrix-signal/pkg/signalmeow.SendMessage({0x16d7a40, 0x1f4a0c0}, 0x0, {0xc0000b6360, 0x24}, 0xc000318dc0)\n\t/builds/mautrix/signal/pkg/signalmeow/sending.go:585 +0xad\nmain.(*Portal).setTyping(0xc0004aa8f0, {0xc000313b00?, 0x1, 0x10?}, 0xa0?)\n\t/builds/mautrix/signal/portal.go:1307 +0x19b\nmain.(*Portal).HandleMatrixTyping(0xc0004aa8f0, {0xc0000371d0, 0x1, 0x1})\n\t/builds/mautrix/signal/portal.go:1322 +0x428\nmaunium.net/go/mautrix/bridge.(*MatrixHandler).HandleTyping(0x0?, 0xc000405520)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.3-0.20231219134117-a27bf782f377/bridge/matrix.go:684 +0xaa\nmaunium.net/go/mautrix/appservice.(*EventProcessor).callHandler(0x0?, 0x0?, 0x0?)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.3-0.20231219134117-a27bf782f377/appservice/eventprocessor.go:102 +0x62\nmaunium.net/go/mautrix/appservice.(*EventProcessor).Dispatch.func2()\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.3-0.20231219134117-a27bf782f377/appservice/eventprocessor.go:153 +0x4d\ncreated by maunium.net/go/mautrix/appservice.(*EventProcessor).Dispatch in goroutine 84\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.16.3-0.20231219134117-a27bf782f377/appservice/eventprocessor.go:151 +0x16b\n"
```

I'm using the `dock.mau.dev/mautrix/signal:latest` docker image.

**Comment by kolaente** [comment]
Interesting to note here is my setup didn't change and was running perfectly fine. I've restarted the docker stack after an upgrade to element 1.11.52 and since then, the error is happening. Downgrading back to 1.11.51 does not fix it so I don't think the problem is caused by the newer element version.

**Comment by kolaente** [comment]
Digging a little more, this line seems to be where the error is happening:

https://github.com/mautrix/signal/blob/3c0482e97f2b506a8d20758240080d5211bfa49b/pkg/signalmeow/sending.go#L659

And there is another error message earlier in the logs which might be related to that:

```
ERR problem looking up aci ebb2bc0e-8c70-41df-8522-8c9be890a846 error="failed to scan session: 40: no key type identifier" user_id=@kolaente:kolaente.de
WRN No device found for user, skipping Connect and sending BadCredentials BridgeState user_id=@kolaente:kolaente.de

**Comment by tulir** [comment]
Some edge cases like trying to send messages while you're not logged in can cause panics, but they're caught so it's fine for now

**Comment by tulir** [comment]
You're probably not logged in if you can't send or receive messages. The error is caught, if it wasn't caught then the bridge would've crashed.

**Comment by kolaente** [comment]
Logged in again and it seems to work fine now. Thanks!
