### ISSUE TITLE
Cannot rejoin left room

### ISSUE THREAD

**Issue by yajo** [mautrix/signal#40]
You can see the problem here:

![imagen](https://user-images.githubusercontent.com/973709/104816400-cf916500-5812-11eb-9ccb-b7608cdc38aa.png)

Full traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 320, in ensure_joined
    await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 79, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
    content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MUnknown: No known servers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/signal.py", line 75, in pm
    await portal.main_intent.invite_user(portal.mxid, evt.sender.mxid)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 90, in wrapper
    await __self.ensure_joined(room_id)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 342, in ensure_joined
    raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix.errors.base.IntentError: Failed to join room !*******:example.com as @signal_*****:example.com
```

**Comment by tacerus** [comment]
I am facing the same issue.

**Comment by ReggieMarr** [comment]
I have a similar problem. Once one of my contacts tried to pm me (where we already had messages going) I lost the ability to get his messages

**Comment by dragonchaser** [comment]
Same issue here.

**Comment by dragonchaser** [comment]
I think the issue happens only with corrupt databases, I could not reproduce it for the last weeks....
