### ISSUE TITLE
 Fatal error while waiting for linking to finish (see logs for more details)

### ISSUE THREAD

**Issue by muellerjoel** [mautrix/signal#438]
```
Traceback (most recent call last):
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mautrix_signal/commands/auth.py", line 180, in register
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mausignald/signald.py", line 167, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mausignald/rpc.py", line 245, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mausignald/rpc.py", line 239, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/mautrix-signal/lib/python3.11/site-packages/mausignald/rpc.py", line 236, in _raw_request
    return await asyncio.shield(future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mausignald.errors.InternalError: error registering with server
```

 **Signald 	0.23.2-1
Linux Kernel 6.7.3
Python 3.11
mautrix-signal 0.4.3**

**Comment by mrclauss** [comment]
Signald is no longer maintained. Please use a newer version of mautrix-signal without signald dependency.
