### ISSUE TITLE
Cannot create portal: "invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CyberPingU** [mautrix/signal#499]
Here is what happens when I try to create a portal with !signal create portal

`mautrix-signal  | 2024-04-15T09:01:14Z ERR Panic in Matrix command handler error="invalid memory address or nil pointer dereference" event_id=$lRi42ujB0VpA3qN-Q-M7fGMR-feGqkneet7SKOsIdMM mx_command=create room_id=!hkcAOLouBbAQMGtNvm:matrix.grtsec.xxx sender=@admin:matrix.grtsec.xxx stack="goroutine 344 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\nmaunium.net/go/mautrix/bridge/commands.(*Processor).Handle.func1()\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.18.1-0.20240322180408-ade00e8603f9/bridge/commands/processor.go:66 +0x5f\npanic({0x17d92c0?, 0x2429430?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\nmain.fnCreate(0xc0006abae8)\n\t/builds/mautrix/signal/commands.go:1106 +0x1584\nmain.init.wrapCommand.func17(0x17e1360?)\n\t/builds/mautrix/signal/commands.go:88 +0x96\nmaunium.net/go/mautrix/bridge/commands.(*FullHandler).Run(0x243ede0, 0xc00057c750)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.18.1-0.20240322180408-ade00e8603f9/bridge/commands/handler.go:98 +0xfb\nmaunium.net/go/mautrix/bridge/commands.(*Processor).Handle(0xc0000bb540, {0x1ab89f8, 0xc00032c720}, {0xc00012ac80, 0x34}, {0xc000661b00, 0x2c}, {0x1abd170, 0xc000316600}, {0xc00003b328, ...}, ...)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.18.1-0.20240322180408-ade00e8603f9/bridge/commands/processor.go:120 +0x87c\ncreated by maunium.net/go/mautrix/bridge.(*MatrixHandler).HandleMessage in goroutine 342\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.18.1-0.20240322180408-ade00e8603f9/bridge/matrix.go:619 +0x9c5\n"`

And sometimes:

`mautrix-signal  | 2024-04-15T09:08:23Z ERR Failed to fetch storage error="failed to unmarshal decrypted storage item #1 (Av6ugDuBESughrTc+3Qphg==): proto: cannot parse invalid wire-format data" action="sync storage" destination_service_id=6ca10de6-f9ed-43bf-a4f3-6c274a44c360 handler="incoming request handler" path=/api/v1/message sender_device_id=1 sender_name=6ca10de6-f9ed-43bf-a4f3-6c274a44c360 user_id=@admin.grtsec.xxx username=6ca10de6-f9ed-43bf-a4f3-6c274a44c360.2 verb=PUT websocket_type=authed`

**Comment by CyberPingU** [comment]
After last pach (15.04.24), portals work with a docker rebuild from sources )`"failed to unmarshal decrypted storage item` persists but it's not related)
