### ISSUE TITLE
bridge crashes with "can't evaluate field Phone in type *connector.DisplaynameParams"

### ISSUE THREAD

**Issue by jwise** [mautrix/signal#530]
The bridge seems to often crash with a stack trace that starts with:

```
panic: template: displayname:1:31: executing "displayname" at <.Phone>: can't evaluate field Phone in type *connector.DisplaynameParams

goroutine 132 [running]:
go.mau.fi/mautrix-signal/pkg/connector.(*SignalConfig).FormatDisplayname(0x27cef20, 0xc00083c000)
        /builds/mautrix/signal/pkg/connector/config.go:70 +0x30b
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).contactToUserInfo(0xc0000d8560, 0xc00083c000)
        /builds/mautrix/signal/pkg/connector/chatinfo.go:81 +0x171
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).handleSignalContactList(0xc0000d8560, 0xc000013380)
        /builds/mautrix/signal/pkg/connector/handlesignal.go:457 +0x4a5
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).handleSignalEvent(0xc0000d8560, {0x1cdbd20?, 0xc000013380?})
        /builds/mautrix/signal/pkg/connector/handlesignal.go:50 +0x165
```

It usually does so within a minute or so of startup.

I run it as follows, with the following version message:

```
joshua@moroso:~/beeper$ ./bbctl-linux-amd64 run sh-jwise-signal
Checking for updates to mautrix-signal from mau.dev
mautrix-signal is up to date (commit: 77c150f7)
Starting signal
Migrating legacy bridge config
2024-08-12T03:12:11.656-04:00 INF Initializing bridge built_at=2024-08-11T19:35:09Z go_version=go1.22.6 name=mautrix-signal version=0.7.0+dev.77c150f7
```

**Comment by tulir** [comment]
Sounds like a configuration issue
