### ISSUE TITLE
Crash nil pointer on incoming messages since v0.7.0

### ISSUE THREAD

**Issue by wrenix** [mautrix/signal#533]
```json
{
  "level": "error",
  "portal_id": "fa243a21-d68d-49c5-b8e3-62ad875860a7",
  "portal_mxid": "!myroom:myhomeserver",
  "action": "handle matrix event",
  "event_type": "m.typing",
  "error": "runtime error: invalid memory address or nil pointer dereference",
  "stack": "goroutine 528 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\nmaunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixEvent.func1()\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:410 +0xe5\npanic({0x19ffc60?, 0x274c5a0?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngo.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).HandleMatrixTyping(0xc000382140, {0x1ce94a0, 0xc00050d020}, 0xc000884240?)\n\t/builds/mautrix/signal/pkg/connector/handlematrix.go:275 +0x161\nmaunium.net/go/mautrix/bridgev2.(*Portal).sendTypings(0xc00036a7e0, {0x1ce94a0, 0xc00050d020}, {0xc0002bea40?, 0xc000518ea0?, 0x1?}, 0x1)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:635 +0x423\nmaunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixTyping(0xc00036a7e0, {0x1ce94a0, 0xc00050d020}, 0x0?)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:598 +0x1b9\nmaunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixEvent(0xc00036a7e0, 0x0, 0xc0004284e0)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:422 +0x4d4\nmaunium.net/go/mautrix/bridgev2.(*Portal).eventLoop(0xc00036a7e0)\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:279 +0xc5\ncreated by maunium.net/go/mautrix/bridgev2.(*Bridge).loadPortal in goroutine 527\n\t/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:129 +0x425\n",
  "time": "2024-08-17T10:11:48.621872594Z",
  "message": "Matrix event handler panicked"
}
```

stack:
```
goroutine 528 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
maunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixEvent.func1()
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:410 +0xe5
panic({0x19ffc60?, 0x274c5a0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).HandleMatrixTyping(0xc000382140, {0x1ce94a0, 0xc00050d020}, 0xc000884240?)
	/builds/mautrix/signal/pkg/connector/handlematrix.go:275 +0x161
maunium.net/go/mautrix/bridgev2.(*Portal).sendTypings(0xc00036a7e0, {0x1ce94a0, 0xc00050d020}, {0xc0002bea40?, 0xc000518ea0?, 0x1?}, 0x1)
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:635 +0x423
maunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixTyping(0xc00036a7e0, {0x1ce94a0, 0xc00050d020}, 0x0?)
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:598 +0x1b9
maunium.net/go/mautrix/bridgev2.(*Portal).handleMatrixEvent(0xc00036a7e0, 0x0, 0xc0004284e0)
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:422 +0x4d4
maunium.net/go/mautrix/bridgev2.(*Portal).eventLoop(0xc00036a7e0)
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:279 +0xc5
created by maunium.net/go/mautrix/bridgev2.(*Bridge).loadPortal in goroutine 527
	/builds/mautrix/signal/.cache/pkg/mod/maunium.net/go/mautrix@v0.20.0/bridgev2/portal.go:129 +0x425

```

**Comment by tobiasdiez** [comment]
I also experience this. Thanks for the quick fix! Could we get a new release soon please?

**Comment by tulir** [comment]
No, https://docs.mau.fi/bridges/general/troubleshooting.html#why-is-the-latest-release-old
