### ISSUE TITLE
Failed to fetch profile / .Phone

### ISSUE THREAD

**Issue by tynan** [mautrix/signal#539]
I restarted the bridge, which updated it to the newest version, and got this error:

```
DBG Failed to fetch profile error="profile key not found" action="fetch contact then try and update with profile" login_id=[REDACTED] profile_aci=[REDACTED] user_mxid=@[REDACTED BEEPER ADDRESS]
panic: template: displayname:1:31: executing "displayname" at <.Phone>: can't evaluate field Phone in type *connector.DisplaynameParams

goroutine 16 [running]:
go.mau.fi/mautrix-signal/pkg/connector.(*SignalConfig).FormatDisplayname(0x27d7fc0, 0xc000590d80)
        /builds/mautrix/signal/pkg/connector/config.go:70 +0x30b
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).contactToUserInfo(0xc0001582e0, 0xc000590d80)
        /builds/mautrix/signal/pkg/connector/chatinfo.go:93 +0x1c9
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).handleSignalContactList(0xc0001582e0, 0xc000013c68)
        /builds/mautrix/signal/pkg/connector/handlesignal.go:457 +0x4a5
go.mau.fi/mautrix-signal/pkg/connector.(*SignalClient).handleSignalEvent(0xc0001582e0, {0x1ce3e80?, 0xc000013c68?})  
        /builds/mautrix/signal/pkg/connector/handlesignal.go:50 +0x165
go.mau.fi/mautrix-signal/pkg/signalmeow.(*Client).handleEvent(...)
        /builds/mautrix/signal/pkg/signalmeow/client.go:63
go.mau.fi/mautrix-signal/pkg/signalmeow.(*Client).handleDecryptedResult(0xc00024d520, {0x1cea7e0, 0xc0002fe900}, {0xc0002489f0, 0xc00041cdc0, 0x0, {0x0, 0x0}, 0x0}, {0x0, ...})
        /builds/mautrix/signal/pkg/signalmeow/receiving.go:786 +0x1d98
go.mau.fi/mautrix-signal/pkg/signalmeow.(*Client).incomingAPIMessageHandler(0xc00024d520, {0x1cea7e0, 0xc0002fe900}, 0xc000254f50)
        /builds/mautrix/signal/pkg/signalmeow/receiving.go:289 +0x3cd
go.mau.fi/mautrix-signal/pkg/signalmeow.(*Client).incomingRequestHandler(0xc00024d520, {0x1cea818, 0xc0000aaaf0}, 0xc000254f50)
        /builds/mautrix/signal/pkg/signalmeow/receiving.go:257 +0x42d
go.mau.fi/mautrix-signal/pkg/signalmeow/web.(*SignalWebsocket).connectLoop.func2()
        /builds/mautrix/signal/pkg/signalmeow/web/signalwebsocket.go:166 +0x1e2
created by go.mau.fi/mautrix-signal/pkg/signalmeow/web.(*SignalWebsocket).connectLoop in goroutine 77
        /builds/mautrix/signal/pkg/signalmeow/web/signalwebsocket.go:146 +0x48b`
```

**Comment by tulir** [comment]
That happens if you use a very old version of bbctl

**Comment by vale981** [comment]
I get the same error without bbctl. I'm using the ansible docker playbook on the latest version.

``DBG Failed to fetch profile error="profile key not found" action="fetch contact then try and update with profile" login_id=... profile_aci=... user_mxid=...``

**Comment by tulir** [comment]
That's a debug log, it just means you don't have access to the user's profile

**Comment by vale981** [comment]
It also pops up as an ERR. But if it's nothing to worry about, it's fine by me. Could you point me to the code that produces that error?
