### ISSUE TITLE
error while syncing own puppet

### ISSUE THREAD

**Issue by Pecadis** [mautrix/signal#65]
Hi everyone,

i could setup the bot now but when i try to add the access token to the bot, the message following message comes up.

```
Feb 16 17:53:06 matrix-signal python[17519]: [2021-02-16 17:53:06,456] [ERROR@mau.user.@me:example.com] Error while syncing own puppet
Feb 16 17:53:06 matrix-signal python[17519]: Traceback (most recent call last):
Feb 16 17:53:06 matrix-signal python[17519]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix_signal/user.py", line 127, in sync
Feb 16 17:53:06 matrix-signal python[17519]:     await self._sync_puppet()
Feb 16 17:53:06 matrix-signal python[17519]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix_signal/user.py", line 123, in _sync_puppet
Feb 16 17:53:06 matrix-signal python[17519]:     await puppet.switch_mxid(access_token="auto", mxid=self.mxid)
Feb 16 17:53:06 matrix-signal python[17519]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 172, in switch_mxid
Feb 16 17:53:06 matrix-signal python[17519]:     access_token = await self._login_with_shared_secret(mxid)
Feb 16 17:53:06 matrix-signal python[17519]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 156, in _login_with_shared_secret
Feb 16 17:53:06 matrix-signal python[17519]:     data = await resp.json()
Feb 16 17:53:06 matrix-signal python[17519]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1103, in json
Feb 16 17:53:06 matrix-signal python[17519]:     headers=self.headers,
Feb 16 17:53:06 matrix-signal python[17519]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://subdomain.example.com/login')
```

The curious point is the last line where it tries to get something from my subdomain. It looks like it's being redirected the wrong way or is collecting some wrong information's from the root domain "example.com". When looking at the .well-known/matrix/server directive, it seems to be fine, at least the whatsapp-bridge could use the Auth-token just well.

Is there anything i can do to investigate here?

**Comment by tulir** [comment]
Did you set an incorrect URL in `double_puppet_server_map` or something like that?

Clients don't use the `server` well-known file, they use `/.well-known/matrix/client`, but for users on the same server as the bridge, it should use `homeserver`->`address` by default.

**Comment by Pecadis** [comment]
Thanks @tulir that was the point. i was referring there to example.com instead of matrix.example.com but a similar issue with the same result comes up where the error says

```
[ERROR@mau.puppet.56fc7239-3bfc-4bcb-9671-85240e69f632] Failed to initialize custom mxid
Feb 19 22:10:02 matrix-signal python[20516]: Traceback (most recent call last):
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/api.py", line 233, in request
Feb 19 22:10:02 matrix-signal python[20516]:     return await self._send(method, full_url, content, query_params, headers or {})
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/api.py", line 169, in _send
Feb 19 22:10:02 matrix-signal python[20516]:     return await response.json()
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1103, in json
Feb 19 22:10:02 matrix-signal python[20516]:     headers=self.headers,
Feb 19 22:10:02 matrix-signal python[20516]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://subdomain.example.com/login')
Feb 19 22:10:02 matrix-signal python[20516]: The above exception was the direct cause of the following exception:
Feb 19 22:10:02 matrix-signal python[20516]: Traceback (most recent call last):
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 217, in try_start
Feb 19 22:10:02 matrix-signal python[20516]:     await self.start(retry_auto_login=retry_auto_login)
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 228, in start
Feb 19 22:10:02 matrix-signal python[20516]:     mxid = await self.intent.whoami()
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
Feb 19 22:10:02 matrix-signal python[20516]:     resp = await self.api.request(Method.GET, Path.account.whoami)
Feb 19 22:10:02 matrix-signal python[20516]:   File "/opt/mautrix-signal/lib/python3.7/site-packages/mautrix/api.py", line 235, in request
Feb 19 22:10:02 matrix-signal python[20516]:     raise MatrixConnectionError(str(e)) from e
Feb 19 22:10:02 matrix-signal python[20516]: mautrix.errors.base.MatrixConnectionError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://subdomain.example.com/login')
```

i have played around with "domain" to point to matrix.example.com but that just ran into other issues.
what would be the proper way to get this straight?

Thanks for your work =)
