### ISSUE TITLE
Security keys changed in signal -> communication lost in matrix

### ISSUE THREAD

**Issue by Yajo** [mautrix/signal#75]
Recently on a couple of chats with my contacts, this message appeared:

![imagen](https://user-images.githubusercontent.com/973709/112727841-48502400-8f1c-11eb-9288-996ddf9eba1b.png)

(screenshot is Signal, the message in English is something like "Your security keys with XXXX have changed", the dialog appears when clicking on "Saber más" ("know more")).

Since that moment onwards, bridge stopped working with them:

- Incoming messages not bridged to room.
- Outgoing messages also not bridged.
- Deleting matrix room and reopening (pm): same situation.
- Deleting chat on Signal and reopening room in matrix: same situation.

Any clue on how to restore communication with those contacts? 😢

**Comment by thefinn93** [comment]
This is a bug in signald. [I filed #150 to track](https://gitlab.com/signald/signald/-/issues/150).

**Comment by dubwoc** [comment]
I am seeing a similar behavior on my side with a version of signald that is later than what is referenced in the bug @thefinn93 mentioned. Bug says 0.13.1 and I am running 0.14.0+git2021-07-20r22770696.4. 

The scenario is similar to the above with my one contact that is not working, new phone, changed keys, and now messages sent via the bridge are not delivered but messages with all my other contacts and groups work without problem. 

I noticed a stacktrace that may or may not be related as it happened around the same time so ill put it here as a reference as it is happening as part of syncing contacts, which seems plausibly related:

mautrix-signal 0.1.1+dev.22c9b1a3  stacktrace:
```
[2021-07-23 18:16:30,995] [DEBUG@mausignald] Sync message includes contacts meta, syncing contacts...
[2021-07-23 18:16:32,086] [ERROR@mau.user.@dubwoc:matrix.clevar.cloud] Error while syncing contacts
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_signal/user.py", line 177, in sync_contacts
    await self._sync_contacts()
  File "/usr/lib/python3.9/site-packages/mautrix_signal/user.py", line 224, in _sync_contacts
    for contact in await self.bridge.signal.list_contacts(self.username):
  File "/opt/mautrix-signal/mausignald/signald.py", line 168, in list_contacts
    resp = await self.request_v1("list_contacts", account=username)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 221, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 215, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 212, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: ConcurrentModificationException: no message, see signald logs
```



signald 0.14.0+git2021-07-20r22770696.4 stacktrace:
```
17:15:42.499 [Thread-4] INFO  io.finn.signald.clientprotocol.ClientConnection - signald received a request (request ID: 9bb9890d-7df4-4388-b68e-385f714172db) with no version. This will stop working in a future version of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versioning/
17:16:32.085 [52282603-ecb1-48b7-8085-bbfa3016c3b3-list_contacts] ERROR list_contacts - error while handling request
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?]
	at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:48) ~[signald.jar:unspecified]
	at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:35) ~[signald.jar:unspecified]
	at io.finn.signald.clientprotocol.Request.<init>(Request.java:157) [signald.jar:unspecified]
	at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:141) [signald.jar:unspecified]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by dubwoc** [comment]
I ended up going to the signal app, realizing I hadn't verified my pin in some time and thus forgot it, reset it and the chat worked again on my side so the above is likely a red herring. To confirm, I longer have an issue, thank you!
