### ISSUE TITLE
Register with captcha failing: a captcha token is required to register

### ISSUE THREAD

**Issue by frebib** [mautrix/signal#78]
I've never been able to set up this bridge successfully. I thought I'd give 70ea3527c563785270601f91a98488e7381135df a try but I'm still having no luck:
```
[2021-03-29 13:07:04,762] [ERROR@mau.commands] Unhandled error while handling command register -c signalcaptcha://<snip> +44<snip> from @frebib:chat.nerdhouse.io (ref: 1617022944)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 107, in register
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
  File "/opt/mautrix-signal/mausignald/signald.py", line 104, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 210, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 201, in _raw_request
    return await future
mausignald.errors.ResponseError: a captcha token is required to register
```

**Comment by tulir** [comment]
You need to remove the `signalcaptcha://` part

**Comment by frebib** [comment]
I tried that, although it's not immediately obvious that I had to.
I put `signald` into verbose mode and it's at least receiving the captcha token, so I presume this is a bug with signald, not mautrix-signal?
```
13:36:43.223 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
13:37:10.430 [socketlistener] DEBUG io.finn.signald.SocketHandler - {"id": "506c3351-df5f-45e9-85e9-b739da15c3c9", "type": "register", "version": "v1", "account": "+44<snip>", "voice": false, "captcha": "<the string I entered>"}
13:37:10.487 [socketlistener] INFO  manager-***********10 - Creating new manager for ***********10
13:37:10.494 [socketlistener] INFO  new-account-manager - Created a manager for ***********10
```

**Comment by tommes0815** [comment]
I just set up the signal bridge. I have not used signal before and registered using a captcha. I used the info from the original PR    #59 and it worked for me.

**Comment by celevra** [comment]
any news on that how to pass the captcha url from https://signalcaptchas.org/registration/generate.html ?
