### ISSUE TITLE
One room not working.

### ISSUE THREAD

**Issue by chagai95** [mautrix/signal#84]
Here is the error related to the problem I think
```
Mai 05 08:31:38 localhost.localdomain matrix-mautrix-signal[12719]: [2021-05-05 06:31:38,522] [INFO@aiohttp.access] 172.18.0.12 [05/May/2021:06:31:38 +0000] "PUT /transactions/1811?a
lines 702-747/785 95%
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: raise make_request_error(http_status=response.status,
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: mautrix.errors.request.MForbidden: You are not invited to this room.
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: The above exception was the direct cause of the following exception:
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: Traceback (most recent call last):
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/opt/mautrix-signal/mausignald/signald.py", line 51, in _run_event_handler
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await handler(event)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 50, in on_message
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await self.handle_message(user, sender, evt.data_message)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 99, in handle_message
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await portal.handle_signal_message(user, sender, msg)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 398, in handle_signal_message
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await intent.set_typing(self.mxid, False)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 262, in set_typing
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await self.ensure_joined(room_id)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 341, in ensure_joined
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await bot.invite_user(room_id, self.mxid)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: await __self.ensure_joined(room_id)
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 339, in ensure_joined
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
Mai 05 08:06:51 localhost.localdomain matrix-mautrix-signal[12719]: mautrix.errors.base.IntentError: Failed to join room !wVDUMhsmdJyOQdwful:chagai.website as @signalbot:chagai.website

```

**Comment by woodzman** [comment]
need this solved too..
